package th.co.geniustree.trademark.ocr.domain;

// Generated Feb 4, 2014 9:40:41 AM by Hibernate Tools 3.4.0.CR1


import javax.persistence.*;
import java.util.Objects;

/**
 * CtltAgency generated by hbm2java
 */
@Entity
@Table(name = "CTLT_AGENCY")
public class CtltAgency extends BaseEntity implements java.io.Serializable {

    private static final long serialVersionUID = 6252943126404531998L;
    @Id
    @SequenceGenerator(name = "CTLT_AGENCY_SEQ", sequenceName = "CTLT_AGENCY_SEQ", initialValue = 1, allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "CTLT_AGENCY_SEQ")
    @Column(name = "AGEN_ID", unique = true, nullable = false, precision = 15, scale = 0)
    private Long agenId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "LOC_ID")
    private CtltLocation ctltLocation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "OCCU_ID")
    private CtltOccupation ctltOccupation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "NAT_ID")
    private CtltNation ctltNation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "COUNTRY_ID")
    private CtltCountry ctltCountry;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "AGEN_GRP_ID")
    private CtltAgencyGrp ctltAgencyGrp;

    @Column(name = "AGEN_TYPE", length = 1)
    private String agenType;

    @Column(name = "AGEN_NAME", length = 150)
    private String agenName;

    @Column(name = "AGEN_CARD_NO", length = 50)
    private String agenCardNo;

    @Column(name = "AGEN_ADDR")
    private String agenAddr;

    @Column(name = "AGEN_POSTCODE", length = 10)
    private String agenPostcode;

    @Column(name = "AGEN_PHONE", length = 50)
    private String agenPhone;

    @Column(name = "AGEN_FAX", length = 50)
    private String agenFax;

    @Column(name = "AGEN_EMAIL", length = 150)
    private String agenEmail;

    @Column(name = "USE_FLAG", length = 1)
    private String useFlag;

    @Column(name = "AGEN_CARD_TYPE", length = 1)
    private String agenCardType;

    @Column(name = "AGEN_GENDER", length = 1)
    private String agenGender;

    @Column(name = "AGEN_TYPE_DET", length = 150)
    private String agenTypeDet;

    @Column(name = "LOC_CODE", length = 8)
    private String locCode;

    @Column(name = "AGEN_KIND", length = 1)
    private String agenKind;

    public CtltAgency() {
    }

    public CtltAgency(Long agenId) {
        this.agenId = agenId;
    }

    @Transient
    public Long getPk() {
        return agenId;
    }


    public Long getAgenId() {
        return this.agenId;
    }

    public void setAgenId(Long agenId) {
        this.agenId = agenId;
    }

    public CtltLocation getCtltLocation() {
        return this.ctltLocation;
    }

    public void setCtltLocation(CtltLocation ctltLocation) {
        this.ctltLocation = ctltLocation;
    }

    public CtltOccupation getCtltOccupation() {
        return this.ctltOccupation;
    }

    public void setCtltOccupation(CtltOccupation ctltOccupation) {
        this.ctltOccupation = ctltOccupation;
    }

    public CtltNation getCtltNation() {
        return this.ctltNation;
    }

    public void setCtltNation(CtltNation ctltNation) {
        this.ctltNation = ctltNation;
    }

    public CtltCountry getCtltCountry() {
        return this.ctltCountry;
    }

    public void setCtltCountry(CtltCountry ctltCountry) {
        this.ctltCountry = ctltCountry;
    }

    public CtltAgencyGrp getCtltAgencyGrp() {
        return this.ctltAgencyGrp;
    }

    public void setCtltAgencyGrp(CtltAgencyGrp ctltAgencyGrp) {
        this.ctltAgencyGrp = ctltAgencyGrp;
    }

    public String getAgenType() {
        return this.agenType;
    }

    public void setAgenType(String agenType) {
        this.agenType = agenType;
    }

    public String getAgenName() {
        return this.agenName;
    }

    public void setAgenName(String agenName) {
        this.agenName = agenName;
    }

    public String getAgenCardNo() {
        return this.agenCardNo;
    }

    public void setAgenCardNo(String agenCardNo) {
        this.agenCardNo = agenCardNo;
    }

    public String getAgenAddr() {
        return this.agenAddr;
    }

    public void setAgenAddr(String agenAddr) {
        this.agenAddr = agenAddr;
    }

    public String getAgenPostcode() {
        return this.agenPostcode;
    }

    public void setAgenPostcode(String agenPostcode) {
        this.agenPostcode = agenPostcode;
    }

    public String getAgenPhone() {
        return this.agenPhone;
    }

    public void setAgenPhone(String agenPhone) {
        this.agenPhone = agenPhone;
    }

    public String getAgenFax() {
        return this.agenFax;
    }

    public void setAgenFax(String agenFax) {
        this.agenFax = agenFax;
    }

    public String getAgenEmail() {
        return this.agenEmail;
    }

    public void setAgenEmail(String agenEmail) {
        this.agenEmail = agenEmail;
    }

    public String getUseFlag() {
        return this.useFlag;
    }

    public void setUseFlag(String useFlag) {
        this.useFlag = useFlag;
    }

    public String getAgenCardType() {
        return this.agenCardType;
    }

    public void setAgenCardType(String agenCardType) {
        this.agenCardType = agenCardType;
    }

    public String getAgenGender() {
        return this.agenGender;
    }

    public void setAgenGender(String agenGender) {
        this.agenGender = agenGender;
    }

    public String getAgenTypeDet() {
        return this.agenTypeDet;
    }

    public void setAgenTypeDet(String agenTypeDet) {
        this.agenTypeDet = agenTypeDet;
    }

    public String getLocCode() {
        return this.locCode;
    }

    public void setLocCode(String locCode) {
        this.locCode = locCode;
    }

    public String getAgenKind() {
        return this.agenKind;
    }

    public void setAgenKind(String agenKind) {
        this.agenKind = agenKind;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 23 * hash + Objects.hashCode(this.agenId);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final CtltAgency other = (CtltAgency) obj;
        if (!Objects.equals(this.agenId, other.agenId)) {
            return false;
        }
        return true;
    }

}
