package th.co.geniustree.trademark.ocr.domain;

// Generated Jan 15, 2014 10:11:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.io.Serializable;
import java.util.Objects;

/**
 * CtltOrganize generated by hbm2java
 */
@Entity
@Table(name = "CTLT_ORGANIZE")
public class CtltOrganize extends BaseEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @SequenceGenerator(name = "CTLT_ORGANIZE_SEQ", sequenceName = "CTLT_ORGANIZE_SEQ", initialValue = 1, allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "CTLT_ORGANIZE_SEQ")
    @Column(name = "ORG_ID", unique = true, nullable = false, precision = 15, scale = 0)
    private Long orgId;

    @Column(name = "ORG_CODE", length = 18)
    private String orgCode;

    @Column(name = "ORG_LEVEL", length = 1)
    private String orgLevel;

    @Column(name = "ORG_NAME", length = 150)
    private String orgName;

    @Column(name = "ORG_TYPE", length = 1)
    private String orgType;

    @Column(name = "USE_FLAG", length = 1)
    private String useFlag;

    public Long getOrgId() {
        return orgId;
    }

    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    public String getOrgCode() {
        return orgCode;
    }

    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    public String getOrgLevel() {
        return orgLevel;
    }

    public void setOrgLevel(String orgLevel) {
        this.orgLevel = orgLevel;
    }

    public String getOrgName() {
        return orgName;
    }

    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    public String getOrgType() {
        return orgType;
    }

    public void setOrgType(String orgType) {
        this.orgType = orgType;
    }

    public String getUseFlag() {
        return useFlag;
    }

    public void setUseFlag(String useFlag) {
        this.useFlag = useFlag;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CtltOrganize that = (CtltOrganize) o;
        return Objects.equals(orgId, that.orgId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(orgId);
    }
}
