package th.co.geniustree.trademark.ocr.domain;

// Generated Jun 26, 2014 9:16:50 AM by Hibernate Tools 3.4.0.CR1


import javax.persistence.*;
import java.util.Date;
import java.util.Objects;

/**
 * CtltRecvJob generated by hbm2java
 */
@Entity
@Table(name = "CTLT_RECV_JOB")
public class CtltRecvJob extends BaseEntity implements java.io.Serializable {

    @Id
    @SequenceGenerator(name = "CTLT_RECV_JOB_SEQ", sequenceName = "CTLT_RECV_JOB_SEQ", initialValue = 1, allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "CTLT_RECV_JOB_SEQ")
    @Column(name = "JOB_ID", unique = true, nullable = false, precision = 15, scale = 0)
    private Long jobId;

    @Column(name = "TR_NO", precision = 15, scale = 0)
    private Long trNo;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SEND_ORG_ID")
    private CtltOrganize sendCtltOrganize;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SEND_PERSON_ID")
    private CtltOfficer sendCtltOfficer;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "RECV_ORG_ID")
    private CtltOrganize recvCtltOrganize;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "RECV_PERSON_ID")
    private CtltOfficer recvCtltOfficer;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TR_ID")
    private RpstTrademark rpstTrademark;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ACT_ID")
    private CtltAction ctltAction;

    @Column(name = "ACT_DESC", length = 2000)
    private String actDesc;

    @Temporal(TemporalType.DATE)
    @Column(name = "SEND_DATE", length = 7)
    private Date sendDate;

    @Temporal(TemporalType.DATE)
    @Column(name = "RECV_DATE", length = 7)
    private Date recvDate;

    @Column(name = "RECV_STATUS", length = 1)
    private String recvStatus;

    @Column(name = "ACT_CODE", length = 10)
    private String actCode;

    @Column(name = "FEE_CODE", length = 3)
    private String feeCode;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "RECV_ID")
    private SistRecvTm sistRecvTm;

    @Column(name = "RESP_DESC", length = 500)
    private String respDesc;

    @Column(name = "FORM_TYPE", length = 5)
    private String formType;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SCAN_ID")
    private CtstScan ctstScan;

    @Column(name = "UPDATE_BY_PRG", length = 20)
    private String updateByPrg;

    @Column(name = "CREATE_BY_TAB", length = 50)
    private String createByTab;

    @Column(name = "CREATE_BY_PK", precision = 15, scale = 0)
    private Long createByPk;

    @Temporal(TemporalType.DATE)
    @Column(name = "TR_NOX_DATE", length = 7)
    private Date trNoxDate;

    public CtltRecvJob() {
    }

    public CtltRecvJob(Long jobId) {
        this.jobId = jobId;
    }

    public CtltRecvJob(Long jobId, RpstTrademark rpstTrademark) {
        this.jobId = jobId;
        this.rpstTrademark = rpstTrademark;
    }

    @Transient
    public Long getPk() {
        return jobId;
    }

    public Long getJobId() {
        return this.jobId;
    }

    public void setJobId(Long jobId) {
        this.jobId = jobId;
    }

    public Long getTrNo() {
        return this.trNo;
    }

    public void setTrNo(Long trNo) {
        this.trNo = trNo;
    }

    public RpstTrademark getRpstTrademark() {
        return this.rpstTrademark;
    }

    public void setRpstTrademark(RpstTrademark rpstTrademark) {
        this.rpstTrademark = rpstTrademark;
    }

    public String getActDesc() {
        return this.actDesc;
    }

    public void setActDesc(String actDesc) {
        this.actDesc = actDesc;
    }

    public Date getSendDate() {
        return this.sendDate;
    }

    public void setSendDate(Date sendDate) {
        this.sendDate = sendDate;
    }

    public Date getRecvDate() {
        return this.recvDate;
    }

    public void setRecvDate(Date recvDate) {
        this.recvDate = recvDate;
    }

    public String getRecvStatus() {
        return this.recvStatus;
    }

    public void setRecvStatus(String recvStatus) {
        this.recvStatus = recvStatus;
    }

    public String getActCode() {
        return this.actCode;
    }

    public void setActCode(String actCode) {
        this.actCode = actCode;
    }

    public String getFeeCode() {
        return this.feeCode;
    }

    public void setFeeCode(String feeCode) {
        this.feeCode = feeCode;
    }

    public String getRespDesc() {
        return this.respDesc;
    }

    public void setRespDesc(String respDesc) {
        this.respDesc = respDesc;
    }

    public String getFormType() {
        return this.formType;
    }

    public void setFormType(String formType) {
        this.formType = formType;
    }

    public CtltOrganize getSendCtltOrganize() {
        return sendCtltOrganize;
    }

    public void setSendCtltOrganize(CtltOrganize sendCtltOrganize) {
        this.sendCtltOrganize = sendCtltOrganize;
    }

    public CtltOfficer getSendCtltOfficer() {
        return sendCtltOfficer;
    }

    public void setSendCtltOfficer(CtltOfficer sendCtltOfficer) {
        this.sendCtltOfficer = sendCtltOfficer;
    }

    public CtltOrganize getRecvCtltOrganize() {
        return recvCtltOrganize;
    }

    public void setRecvCtltOrganize(CtltOrganize recvCtltOrganize) {
        this.recvCtltOrganize = recvCtltOrganize;
    }

    public CtltOfficer getRecvCtltOfficer() {
        return recvCtltOfficer;
    }

    public void setRecvCtltOfficer(CtltOfficer recvCtltOfficer) {
        this.recvCtltOfficer = recvCtltOfficer;
    }

    public CtltAction getCtltAction() {
        return ctltAction;
    }

    public void setCtltAction(CtltAction ctltAction) {
        this.ctltAction = ctltAction;
    }

    public SistRecvTm getSistRecvTm() {
        return sistRecvTm;
    }

    public void setSistRecvTm(SistRecvTm sistRecvTm) {
        this.sistRecvTm = sistRecvTm;
    }

    public CtstScan getCtstScan() {
        return ctstScan;
    }

    public void setCtstScan(CtstScan ctstScan) {
        this.ctstScan = ctstScan;
    }

    public String getUpdateByPrg() {
        return updateByPrg;
    }

    public void setUpdateByPrg(String updateByPrg) {
        this.updateByPrg = updateByPrg;
    }

    public String getCreateByTab() {
        return createByTab;
    }

    public void setCreateByTab(String createByTab) {
        this.createByTab = createByTab;
    }

    public Long getCreateByPk() {
        return createByPk;
    }

    public void setCreateByPk(Long createByPk) {
        this.createByPk = createByPk;
    }

    public Date getTrNoxDate() {
        return trNoxDate;
    }

    public void setTrNoxDate(Date trNoxDate) {
        this.trNoxDate = trNoxDate;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 79 * hash + Objects.hashCode(this.jobId);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final CtltRecvJob other = (CtltRecvJob) obj;
        if (!Objects.equals(this.jobId, other.jobId)) {
            return false;
        }
        return true;
    }


}
