package th.co.geniustree.trademark.ocr.domain;

// default package
// Generated Jul 22, 2014 10:22:30 AM by Hibernate Tools 3.4.0.CR1


import javax.persistence.*;
import java.util.Objects;

/**
 * CtltAction generated by hbm2java
 */
@Entity
@Table(name = "CTLT_ACTION")
public class CtltAction extends BaseEntity implements java.io.Serializable {

    private static final long serialVersionUID = -828676987087289279L;

    @Id
    @SequenceGenerator(name = "CTLT_ACTION_SEQ", sequenceName = "CTLT_ACTION_SEQ", initialValue = 1, allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "CTLT_ACTION_SEQ")
    @Column(name = "ACT_ID", unique = true, nullable = false, precision = 15, scale = 0)
    private Long actId;

    @Column(name = "ACT_CODE", length = 10)
    private String actCode;

    @Column(name = "ACT_DESC")
    private String actDesc;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ORG_ID")
    private CtltOrganize ctltOrganize;

    @Column(name = "ORG_CODE", length = 18)
    private String orgCode;

    @Column(name = "USE_FLAG", length = 1)
    private String useFlag;

    public CtltAction() {
    }

    public CtltAction(Long actId) {
        this.actId = actId;
    }

    @Transient
    public Long getPk() {
        return actId;
    }

    public Long getActId() {
        return this.actId;
    }

    public void setActId(Long actId) {
        this.actId = actId;
    }

    public String getActCode() {
        return this.actCode;
    }

    public void setActCode(String actCode) {
        this.actCode = actCode;
    }

    public String getActDesc() {
        return this.actDesc;
    }

    public void setActDesc(String actDesc) {
        this.actDesc = actDesc;
    }

    public CtltOrganize getCtltOrganize() {
        return ctltOrganize;
    }

    public void setCtltOrganize(CtltOrganize ctltOrganize) {
        this.ctltOrganize = ctltOrganize;
    }

    public String getOrgCode() {
        return this.orgCode;
    }

    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    public String getUseFlag() {
        return this.useFlag;
    }

    public void setUseFlag(String useFlag) {
        this.useFlag = useFlag;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 29 * hash + Objects.hashCode(this.actId);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final CtltAction other = (CtltAction) obj;
        if (!Objects.equals(this.actId, other.actId)) {
            return false;
        }
        return true;
    }

}
