package th.co.geniustree.trademark.ocr.domain;

// Generated Jun 25, 2014 3:52:21 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Objects;

/**
 * RpstTkCode generated by hbm2java
 */
@Entity
@Table(name = "RPST_TK_CODE", uniqueConstraints = @UniqueConstraint(columnNames = {"TK_CODE", "TK_NO", "MATRA","ACT_YEAR"}))
public class RpstTkCode extends BaseEntity implements java.io.Serializable{
    private static final long serialVersionUID = -4283755497114108286L;

    @Id
    @SequenceGenerator(name = "RPST_TK_CODE_SEQ", sequenceName = "RPST_TK_CODE_SEQ", initialValue = 1, allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "RPST_TK_CODE_SEQ")
    @Column(name = "TK_ID", unique = true, nullable = false, precision = 22, scale = 0)
    private Long tkId;

    @Column(name = "TK_CODE", precision = 2, scale = 0)
    private Long tkCode;

    @Column(name = "TK_NO", precision = 4)
    private BigDecimal tkNo;

    @Column(name = "TK_TYPE", length = 1)
    private String tkType;

    @Column(name = "TK_HEADER", length = 100)
    private String tkHeader;

    @Column(name = "MATRA", length = 15)
    private String matra;

    @Column(name = "MATRA_DESC", length = 500)
    private String matraDesc;

    @Column(name = "RIGHT_DESC", length = 500)
    private String rightDesc;

    @Column(name = "USE_FLAG", length = 1)
    private String useFlag;

    @Column(name = "DAY_LIMIT", precision = 3, scale = 0)
    private Long dayLimit;

    @Column(name = "RIGHT_DAY_LIMIT", precision = 3, scale = 0)
    private Long rightDayLimit;

    @Column(name = "UPDATE_BY_PRG", length = 20)
    private String updateByPrg;

    @Column(name = "WARNING", length = 500)
    private String warning;

    @Column(name = "MATRA_DESC2", length = 500)
    private String matraDesc2;

    @Column(name = "CONDITION_HEADER", length = 500)
    private String conditionHeader;

    @Column(name = "GIST_GRP", length = 1)
    private String gistGrp;

    @Column(name = "ACT_YEAR", length = 4)
    private String actYear;

    public RpstTkCode() {
    }

    public RpstTkCode(Long tkId) {
        this.tkId = tkId;
    }

    public Long getTkId() {
        return this.tkId;
    }

    public void setTkId(Long tkId) {
        this.tkId = tkId;
    }

    public Long getTkCode() {
        return this.tkCode;
    }

    public void setTkCode(Long tkCode) {
        this.tkCode = tkCode;
    }

    public BigDecimal getTkNo() {
        return this.tkNo;
    }

    public void setTkNo(BigDecimal tkNo) {
        this.tkNo = tkNo;
    }

    public String getTkType() {
        return this.tkType;
    }

    public void setTkType(String tkType) {
        this.tkType = tkType;
    }

    public String getTkHeader() {
        return this.tkHeader;
    }

    public void setTkHeader(String tkHeader) {
        this.tkHeader = tkHeader;
    }

    public String getMatra() {
        return this.matra;
    }

    public void setMatra(String matra) {
        this.matra = matra;
    }

    public String getMatraDesc() {
        return this.matraDesc;
    }

    public void setMatraDesc(String matraDesc) {
        this.matraDesc = matraDesc;
    }

    public String getRightDesc() {
        return this.rightDesc;
    }

    public void setRightDesc(String rightDesc) {
        this.rightDesc = rightDesc;
    }

    public String getUseFlag() {
        return this.useFlag;
    }

    public void setUseFlag(String useFlag) {
        this.useFlag = useFlag;
    }

    public Long getDayLimit() {
        return this.dayLimit;
    }

    public void setDayLimit(Long dayLimit) {
        this.dayLimit = dayLimit;
    }

    public Long getRightDayLimit() {
        return this.rightDayLimit;
    }

    public void setRightDayLimit(Long rightDayLimit) {
        this.rightDayLimit = rightDayLimit;
    }

    public String getUpdateByPrg() {
        return this.updateByPrg;
    }

    public void setUpdateByPrg(String updateByPrg) {
        this.updateByPrg = updateByPrg;
    }

    public String getWarning() {
        return this.warning;
    }

    public void setWarning(String warning) {
        this.warning = warning;
    }

    @Transient
    public Long getPk() {
        return tkId;
    }

    public String getMatraDesc2() {
        return matraDesc2;
    }

    public void setMatraDesc2(String matraDesc2) {
        this.matraDesc2 = matraDesc2;
    }

    public String getConditionHeader() {
        return conditionHeader;
    }

    public void setConditionHeader(String conditionHeader) {
        this.conditionHeader = conditionHeader;
    }

    public String getGistGrp() {
        return gistGrp;
    }

    public void setGistGrp(String gistGrp) {
        this.gistGrp = gistGrp;
    }

    public String getActYear() {
        return actYear;
    }

    public void setActYear(String actYear) {
        this.actYear = actYear;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 37 * hash + Objects.hashCode(this.tkId);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final RpstTkCode other = (RpstTkCode) obj;
        if (!Objects.equals(this.tkId, other.tkId)) {
            return false;
        }
        return true;
    }

}
