package th.co.geniustree.trademark.ocr.domain;

// Generated Jun 2, 2014 9:39:20 AM by Hibernate Tools 3.4.0.CR1


import javax.persistence.*;
import java.io.Serializable;
import java.util.Objects;

/**
 * RpstMark generated by hbm2java
 */
@Entity
@Table(name = "RPST_MARK", uniqueConstraints = @UniqueConstraint(columnNames = {"MARK_TYPE", "MARK_CODE"}))
public class RpstMark extends BaseEntity implements Serializable {
    private static final long serialVersionUID = 1957428042083065758L;

    @Id
    @SequenceGenerator(name = "RPST_MARK_SEQ", sequenceName = "RPST_MARK_SEQ", initialValue = 1, allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "RPST_MARK_SEQ")
    @Column(name = "MARK_ID", unique = true, nullable = false, precision = 22, scale = 0)
    private Long markId;

    @Column(name = "MARK_TYPE", nullable = false, length = 1)
    private String markType;

    @Column(name = "MARK_CODE", nullable = false, length = 30)
    private String markCode;

    @Column(name = "MARK_DESC", length = 500)
    private String markDesc;

    @Column(name = "USE_FLAG", length = 1)
    private String useFlag;

    @Column(name = "UPDATE_BY_PRG", length = 20)
    private String updateByPrg;

    public RpstMark() {
    }

    public RpstMark(Long markId) {
        this.markId = markId;
    }

    public RpstMark(Long markId, String markType, String markCode) {
        this.markId = markId;
        this.markType = markType;
        this.markCode = markCode;
    }

    @Transient
    public Long getPk() {
        return markId;
    }

    public Long getMarkId() {
        return this.markId;
    }

    public void setMarkId(Long markId) {
        this.markId = markId;
    }

    public String getMarkType() {
        return this.markType;
    }

    public void setMarkType(String markType) {
        this.markType = markType;
    }

    public String getMarkCode() {
        return this.markCode;
    }

    public void setMarkCode(String markCode) {
        this.markCode = markCode;
    }

    public String getMarkDesc() {
        return this.markDesc;
    }

    public void setMarkDesc(String markDesc) {
        this.markDesc = markDesc;
    }

    public String getUseFlag() {
        return this.useFlag;
    }

    public void setUseFlag(String useFlag) {
        this.useFlag = useFlag;
    }

    public String getUpdateByPrg() {
        return this.updateByPrg;
    }

    public void setUpdateByPrg(String updateByPrg) {
        this.updateByPrg = updateByPrg;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 89 * hash + Objects.hashCode(this.markId);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final RpstMark other = (RpstMark) obj;
        if (!Objects.equals(this.markId, other.markId)) {
            return false;
        }
        return true;
    }

}
