package th.co.geniustree.trademark.ocr.domain;

// Generated May 7, 2014 3:53:10 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.io.Serializable;
import java.util.Objects;

/**
 * RpstTrAgencyRepo generated by hbm2java
 */
@Entity
@Table(name = "RPST_TR_AGENCY")
public class RpstTrAgency extends BaseEntity implements Serializable {

    private static final long serialVersionUID = -1308539694502041794L;


    @Id
    @SequenceGenerator(name = "RPST_TR_AGENCY_SEQ", sequenceName = "RPST_TR_AGENCY_SEQ", initialValue = 1, allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "RPST_TR_AGENCY_SEQ")
    @Column(name = "AGENCY_ID", unique = true, nullable = false, precision = 22, scale = 0)
    private Long agencyId;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "LOC_ID")
    private CtltLocation ctltLocation;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "OCCU_ID")
    private CtltOccupation ctltOccupation;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "TR_ID", nullable = false)
    private RpstTrademark rpstTrademark;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "NAT_ID")
    private CtltNation ctltNation;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "COUNTRY_ID")
    private CtltCountry ctltCountry;

    @Column(name = "TR_NO", nullable = false, precision = 22, scale = 0)
    private Long trNo;

    @Column(name = "SEQ_NO", nullable = false, precision = 22, scale = 0)
    private Long seqNo;

    @Column(name = "PERSON_TYPE", length = 1)
    private String personType;

    @Column(name = "AGENCY_NAME", length = 500)
    private String agencyName;

    @Column(name = "GENDER", length = 1)
    private String gender;

    @Column(name = "NAME_DET", length = 500)
    private String nameDet;

    @Column(name = "CARD_TYPE", length = 1)
    private String cardType;

    @Column(name = "CARD_NO", length = 50)
    private String cardNo;

    @Column(name = "NAT_CODE", length = 50)
    private String natCode;

    @Column(name = "ADDR", length = 500)
    private String addr;

    @Column(name = "LOC_CODE", length = 8)
    private String locCode;

    @Column(name = "POSTCODE", length = 10)
    private String postcode;

    @Column(name = "COUNTRY_CODE", length = 50)
    private String countryCode;

    @Column(name = "PHONE", length = 50)
    private String phone;

    @Column(name = "FAX", length = 50)
    private String fax;

    @Column(name = "EMAIL", length = 200)
    private String email;

    @Column(name = "AGENCY_TYPE", length = 1)
    private String agencyType;

    @Column(name = "UPDATE_BY_PRG", length = 20)
    private String updateByPrg;

    @Column(name = "AND_OR_TYPE", length = 1)
    private String andOrType;

    public RpstTrAgency() {
    }

    public RpstTrAgency(Long agencyId) {
        super();
        this.agencyId = agencyId;
    }

    public Long getAgencyId() {
        return this.agencyId;
    }

    public void setAgencyId(Long agencyId) {
        this.agencyId = agencyId;
    }


    public CtltLocation getCtltLocation() {
        return this.ctltLocation;
    }

    public void setCtltLocation(CtltLocation ctltLocation) {
        this.ctltLocation = ctltLocation;
    }


    public CtltOccupation getCtltOccupation() {
        return this.ctltOccupation;
    }

    public void setCtltOccupation(CtltOccupation ctltOccupation) {
        this.ctltOccupation = ctltOccupation;
    }


    public RpstTrademark getRpstTrademark() {
        return this.rpstTrademark;
    }

    public void setRpstTrademark(RpstTrademark rpstTrademark) {
        this.rpstTrademark = rpstTrademark;
    }

    public CtltNation getCtltNation() {
        return this.ctltNation;
    }

    public void setCtltNation(CtltNation ctltNation) {
        this.ctltNation = ctltNation;
    }

    public CtltCountry getCtltCountry() {
        return this.ctltCountry;
    }

    public void setCtltCountry(CtltCountry ctltCountry) {
        this.ctltCountry = ctltCountry;
    }

    public Long getTrNo() {
        return this.trNo;
    }

    public void setTrNo(Long trNo) {
        this.trNo = trNo;
    }

    public Long getSeqNo() {
        return this.seqNo;
    }

    public void setSeqNo(Long seqNo) {
        this.seqNo = seqNo;
    }

    public String getPersonType() {
        return this.personType;
    }

    public void setPersonType(String personType) {
        this.personType = personType;
    }

    public String getAgencyName() {
        return this.agencyName;
    }

    public void setAgencyName(String agencyName) {
        this.agencyName = agencyName;
    }

    public String getGender() {
        return this.gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getNameDet() {
        return this.nameDet;
    }

    public void setNameDet(String nameDet) {
        this.nameDet = nameDet;
    }

    public String getCardType() {
        return this.cardType;
    }

    public void setCardType(String cardType) {
        this.cardType = cardType;
    }

    public String getCardNo() {
        return this.cardNo;
    }

    public void setCardNo(String cardNo) {
        this.cardNo = cardNo;
    }

    public String getNatCode() {
        return this.natCode;
    }

    public void setNatCode(String natCode) {
        this.natCode = natCode;
    }

    public String getAddr() {
        return this.addr;
    }

    public void setAddr(String addr) {
        this.addr = addr;
    }

    public String getLocCode() {
        return this.locCode;
    }

    public void setLocCode(String locCode) {
        this.locCode = locCode;
    }

    public String getPostcode() {
        return this.postcode;
    }

    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    public String getCountryCode() {
        return this.countryCode;
    }

    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getFax() {
        return this.fax;
    }

    public void setFax(String fax) {
        this.fax = fax;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getAgencyType() {
        return this.agencyType;
    }

    public void setAgencyType(String agencyType) {
        this.agencyType = agencyType;
    }

    public String getUpdateByPrg() {
        return this.updateByPrg;
    }

    public void setUpdateByPrg(String updateByPrg) {
        this.updateByPrg = updateByPrg;
    }


    public String getAndOrType() {
        return andOrType;
    }

    public void setAndOrType(String andOrType) {
        this.andOrType = andOrType;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 11 * hash + Objects.hashCode(this.agencyId);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final RpstTrAgency other = (RpstTrAgency) obj;
        return Objects.equals(this.agencyId, other.agencyId);
    }

}
