package th.co.geniustree.trademark.ocr.domain;

// default package
// Generated Jul 7, 2014 3:51:11 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.io.Serializable;
import java.util.Objects;

/**
 * SistNo01Combine generated by hbm2java
 */
@Entity
@Table(name = "SIST_NO01_COMBINE")
public class SistNo01Combine extends BaseEntity implements Serializable{


    private static final long serialVersionUID = -1051182589950840850L;

    @Id
    @SequenceGenerator(name = "SIST_NO01_COMBINE_SEQ", sequenceName = "SIST_NO01_COMBINE_SEQ", initialValue = 1, allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SIST_NO01_COMBINE_SEQ")
    @Column(name = "COMBINE_ID", unique = true, nullable = false, precision = 15, scale = 0)
    private Long combineId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "LOC_ID")
    private CtltLocation ctltLocation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "OCCU_ID")
    private CtltOccupation ctltOccupation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TR_NO01_ID", nullable = false)
    private SistNo01 sistNo01;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "NAT_ID")
    private CtltNation ctltNation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "COUNTRY_ID")
    private CtltCountry ctltCountry;

    @Column(name = "COMBINE_TYPE", length = 1)
    private String combineType;

    @Column(name = "COMBINE_TYPE_DET")
    private String combineTypeDet;

    @Column(name = "COMBINE_CARD_NO", length = 50)
    private String combineCardNo;

    @Column(name = "COMBINE_CARD_TYPE", length = 1)
    private String combineCardType;

    @Column(name = "COMBINE_NAME", length = 150)
    private String combineName;

    @Column(name = "COMBINE_DET")
    private String combineDet;

    @Column(name = "COMBINE_GENDER", length = 1)
    private String combineGender;

    @Column(name = "COMBINE_ADDR", length = 1000)
    private String combineAddr;

    @Column(name = "LOC_CODE", length = 8)
    private String locCode;

    @Column(name = "COMBINE_POSTCODE", length = 10)
    private String combinePostcode;

    @Column(name = "COMBINE_PHONE", length = 50)
    private String combinePhone;

    @Column(name = "COMBINE_FAX", length = 50)
    private String combineFax;

    @Column(name = "COMBINE_EMAIL", length = 150)
    private String combineEmail;

    @Column(name = "COMBINE_SEQ", precision = 2, scale = 0)
    private Long combineSeq;

    public SistNo01Combine() {
    }

    public SistNo01Combine(Long combineId, SistNo01 sistNo01) {
        this.combineId = combineId;
        this.sistNo01 = sistNo01;
    }

    @Transient
    public Long getPk() {
        return combineId;
    }

    public Long getCombineId() {
        return this.combineId;
    }

    public void setCombineId(Long combineId) {
        this.combineId = combineId;
    }

    public CtltLocation getCtltLocation() {
        return this.ctltLocation;
    }

    public void setCtltLocation(CtltLocation ctltLocation) {
        this.ctltLocation = ctltLocation;
    }

    public CtltOccupation getCtltOccupation() {
        return this.ctltOccupation;
    }

    public void setCtltOccupation(CtltOccupation ctltOccupation) {
        this.ctltOccupation = ctltOccupation;
    }

    public SistNo01 getSistNo01() {
        return this.sistNo01;
    }

    public void setSistNo01(SistNo01 sistNo01) {
        this.sistNo01 = sistNo01;
    }

    public CtltNation getCtltNation() {
        return this.ctltNation;
    }

    public void setCtltNation(CtltNation ctltNation) {
        this.ctltNation = ctltNation;
    }

    public CtltCountry getCtltCountry() {
        return this.ctltCountry;
    }

    public void setCtltCountry(CtltCountry ctltCountry) {
        this.ctltCountry = ctltCountry;
    }

    public String getCombineType() {
        return this.combineType;
    }

    public void setCombineType(String combineType) {
        this.combineType = combineType;
    }

    public String getCombineTypeDet() {
        return this.combineTypeDet;
    }

    public void setCombineTypeDet(String combineTypeDet) {
        this.combineTypeDet = combineTypeDet;
    }

    public String getCombineCardNo() {
        return this.combineCardNo;
    }

    public void setCombineCardNo(String combineCardNo) {
        this.combineCardNo = combineCardNo;
    }

    public String getCombineCardType() {
        return this.combineCardType;
    }

    public void setCombineCardType(String combineCardType) {
        this.combineCardType = combineCardType;
    }

    public String getCombineName() {
        return this.combineName;
    }

    public void setCombineName(String combineName) {
        this.combineName = combineName;
    }

    public String getCombineDet() {
        return this.combineDet;
    }

    public void setCombineDet(String combineDet) {
        this.combineDet = combineDet;
    }

    public String getCombineGender() {
        return this.combineGender;
    }

    public void setCombineGender(String combineGender) {
        this.combineGender = combineGender;
    }

    public String getCombineAddr() {
        return this.combineAddr;
    }

    public void setCombineAddr(String combineAddr) {
        this.combineAddr = combineAddr;
    }

    public String getLocCode() {
        return this.locCode;
    }

    public void setLocCode(String locCode) {
        this.locCode = locCode;
    }

    public String getCombinePostcode() {
        return this.combinePostcode;
    }

    public void setCombinePostcode(String combinePostcode) {
        this.combinePostcode = combinePostcode;
    }

    public String getCombinePhone() {
        return this.combinePhone;
    }

    public void setCombinePhone(String combinePhone) {
        this.combinePhone = combinePhone;
    }

    public String getCombineFax() {
        return this.combineFax;
    }

    public void setCombineFax(String combineFax) {
        this.combineFax = combineFax;
    }

    public String getCombineEmail() {
        return this.combineEmail;
    }

    public void setCombineEmail(String combineEmail) {
        this.combineEmail = combineEmail;
    }

    public Long getCombineSeq() {
        return combineSeq;
    }

    public void setCombineSeq(Long combineSeq) {
        this.combineSeq = combineSeq;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 37 * hash + Objects.hashCode(this.combineId);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final SistNo01Combine other = (SistNo01Combine) obj;
        if (!Objects.equals(this.combineId, other.combineId)) {
            return false;
        }
        return true;
    }


}
