package th.co.geniustree.trademark.ocr.domain;

// Generated Jan 29, 2014 4:37:08 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.Objects;

/**
 * SistNo02Opponent generated by hbm2java
 */
@Entity
@Table(name = "SIST_NO02_OPPONENT")
public class SistNo02Opponent extends BaseEntity implements java.io.Serializable {

    private static final long serialVersionUID = -7318448110576276926L;

    @Id
    @SequenceGenerator(name = "SIST_NO02_OPPONENT_SEQ", sequenceName = "SIST_NO02_OPPONENT_SEQ", initialValue = 1, allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SIST_NO02_OPPONENT_SEQ")
    @Column(name = "OPPONENT_ID", unique = true, nullable = false, precision = 15, scale = 0)
    private Long opponentId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "LOC_ID")
    private CtltLocation ctltLocation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TR_NO02_ID", nullable = false)
    private SistNo02 sistNo02;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "OCCU_ID")
    private CtltOccupation ctltOccupation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "NAT_ID")
    private CtltNation ctltNation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "COUNTRY_ID")
    private CtltCountry ctltCountry;

    @Column(name = "OPPO_TYPE", length = 1)
    private String oppoType;

    @Column(name = "OPPO_TYPE_DET")
    private String oppoTypeDet;

    @Column(name = "OPPO_CARD_NO", length = 50)
    private String oppoCardNo;

    @Column(name = "OPPO_CARD_TYPE", length = 1)
    private String oppoCardType;

    @Column(name = "OPPO_NAME", length = 150)
    private String oppoName;

    @Column(name = "OPPO_DET")
    private String oppoDet;

    @Column(name = "OPPO_GENDER", length = 1)
    private String oppoGender;

    @Column(name = "OPPO_ADDR", length = 1000)
    private String oppoAddr;

    @Column(name = "LOC_CODE", length = 8)
    private String locCode;

    @Column(name = "OPPO_POSTCODE", length = 10)
    private String oppoPostcode;

    @Column(name = "OPPO_PHONE", length = 50)
    private String oppoPhone;

    @Column(name = "OPPO_FAX", length = 50)
    private String oppoFax;

    @Column(name = "OPPO_EMAIL", length = 150)
    private String oppoEmail;

    @Column(name = "OPPO_SEQ", precision = 1, scale = 0)
    private Long oppoSeq;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TRW_OWNER_ID")
    private TrwtNo02Owner trwtNo02Owner;

    public SistNo02Opponent() {
    }

    public SistNo02Opponent(Long opponentId) {
        this.opponentId = opponentId;
    }

    @Transient
    public Long getPk() {
        return opponentId;
    }

    public Long getOpponentId() {
        return this.opponentId;
    }

    public void setOpponentId(Long opponentId) {
        this.opponentId = opponentId;
    }

    public CtltLocation getCtltLocation() {
        return this.ctltLocation;
    }

    public void setCtltLocation(CtltLocation ctltLocation) {
        this.ctltLocation = ctltLocation;
    }

    public SistNo02 getSistNo02() {
        return this.sistNo02;
    }

    public void setSistNo02(SistNo02 sistNo02) {
        this.sistNo02 = sistNo02;
    }

    public CtltOccupation getCtltOccupation() {
        return this.ctltOccupation;
    }

    public void setCtltOccupation(CtltOccupation ctltOccupation) {
        this.ctltOccupation = ctltOccupation;
    }

    public CtltNation getCtltNation() {
        return this.ctltNation;
    }

    public void setCtltNation(CtltNation ctltNation) {
        this.ctltNation = ctltNation;
    }

    public CtltCountry getCtltCountry() {
        return this.ctltCountry;
    }

    public void setCtltCountry(CtltCountry ctltCountry) {
        this.ctltCountry = ctltCountry;
    }

    public String getOppoType() {
        return this.oppoType;
    }

    public void setOppoType(String oppoType) {
        this.oppoType = oppoType;
    }

    public String getOppoTypeDet() {
        return this.oppoTypeDet;
    }

    public void setOppoTypeDet(String oppoTypeDet) {
        this.oppoTypeDet = oppoTypeDet;
    }

    public String getOppoCardNo() {
        return this.oppoCardNo;
    }

    public void setOppoCardNo(String oppoCardNo) {
        this.oppoCardNo = oppoCardNo;
    }

    public String getOppoCardType() {
        return this.oppoCardType;
    }

    public void setOppoCardType(String oppoCardType) {
        this.oppoCardType = oppoCardType;
    }

    public String getOppoName() {
        return this.oppoName;
    }

    public void setOppoName(String oppoName) {
        this.oppoName = oppoName;
    }

    public String getOppoDet() {
        return this.oppoDet;
    }

    public void setOppoDet(String oppoDet) {
        this.oppoDet = oppoDet;
    }

    public String getOppoGender() {
        return this.oppoGender;
    }

    public void setOppoGender(String oppoGender) {
        this.oppoGender = oppoGender;
    }

    public String getOppoAddr() {
        return this.oppoAddr;
    }

    public void setOppoAddr(String oppoAddr) {
        this.oppoAddr = oppoAddr;
    }

    public String getLocCode() {
        return this.locCode;
    }

    public void setLocCode(String locCode) {
        this.locCode = locCode;
    }

    public String getOppoPostcode() {
        return this.oppoPostcode;
    }

    public void setOppoPostcode(String oppoPostcode) {
        this.oppoPostcode = oppoPostcode;
    }

    public String getOppoPhone() {
        return this.oppoPhone;
    }

    public void setOppoPhone(String oppoPhone) {
        this.oppoPhone = oppoPhone;
    }

    public String getOppoFax() {
        return this.oppoFax;
    }

    public void setOppoFax(String oppoFax) {
        this.oppoFax = oppoFax;
    }

    public String getOppoEmail() {
        return this.oppoEmail;
    }

    public void setOppoEmail(String oppoEmail) {
        this.oppoEmail = oppoEmail;
    }

    public Long getOppoSeq() {
        return this.oppoSeq;
    }

    public void setOppoSeq(Long oppoSeq) {
        this.oppoSeq = oppoSeq;
    }

    public TrwtNo02Owner getTrwtNo02Owner() {
        return trwtNo02Owner;
    }

    public void setTrwtNo02Owner(TrwtNo02Owner trwtNo02Owner) {
        this.trwtNo02Owner = trwtNo02Owner;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 29 * hash + Objects.hashCode(this.opponentId);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final SistNo02Opponent other = (SistNo02Opponent) obj;
        if (!Objects.equals(this.opponentId, other.opponentId)) {
            return false;
        }
        return true;
    }

}
