package th.co.geniustree.trademark.ocr.domain;

// Generated Apr 1, 2014 1:32:28 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.*;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.Objects;

/**
 * SistBankImport generated by hbm2java
 */
@Entity
@Table(name = "SIST_BANK_IMPORT")
public class SistBankImport extends BaseEntity implements Serializable {

    private static final long serialVersionUID = 4226260301086237212L;

    @Id
    @SequenceGenerator(name = "SIST_BANK_IMPORT_SEQ", sequenceName = "SIST_BANK_IMPORT_SEQ", initialValue = 1, allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SIST_BANK_IMPORT_SEQ")
    @Column(name = "IMP_ID", unique = true, nullable = false, precision = 15, scale = 0)
    private Long impId;

    @Column(name = "IMP_SEQ", precision = 15, scale = 0)
    private Long impSeq;

    @Temporal(TemporalType.DATE)
    @Column(name = "IMP_DATE", length = 7)
    private Date impDate;

    @Column(name = "BANK_CODE", length = 10)
    private String bankCode;

    @Column(name = "BANK_ABBR", length = 10)
    private String bankAbbr;

    @Column(name = "COMPANY_ACCOUNT", length = 15)
    private String companyAccount;

    @Temporal(TemporalType.DATE)
    @Column(name = "PAYMENT_DATE", length = 7)
    private Date paymentDate;

    @Column(name = "PAYMENT_TIME", length = 8)
    private String paymentTime;

    @Column(name = "CUSTOMER_NAME")
    private String customerName;

    @Column(name = "PAYMENT_NO", precision = 19, scale = 0)
    private Long paymentNo;

    @Column(name = "TELLER_NO", length = 10)
    private String tellerNo;

    @Column(name = "KIND_TRANS", length = 1)
    private String kindTrans;

    @Column(name = "TRANS_CODE", length = 10)
    private String transCode;

    @Column(name = "CHEQUE_NO", precision = 10, scale = 0)
    private Long chequeNo;

    @Column(name = "PAYMENT_AMOUNT", precision = 12)
    private BigDecimal paymentAmount;

    @Column(name = "TOTAL_AMOUNT", precision = 12)
    private BigDecimal totalAmount;

    @Column(name = "TRANS_FLAG", length = 2)
    private String transFlag;

    @Column(name = "RECEIPT_NO", length = 10)
    private String receiptNo;

    @Temporal(TemporalType.DATE)
    @Column(name = "RECEIPT_DATE", length = 7)
    private Date receiptDate;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "RECEIPT_SCAN_ID")
    private CtstScan receiptScanId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PAYINT_ID")
    private SistPaymentint sistPaymentint;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PAYIN_DET_ID")
    private SistPaymentintDet sistPaymentintDet;

    @Column(name = "RECEIPT_BOOK", length = 10)
    private String receiptBook;

    public SistBankImport() {
    }

    public SistBankImport(Long impId) {
        this.impId = impId;
    }

    @Transient
    public Long getPk() {
        return impId;
    }

    public Long getImpId() {
        return this.impId;
    }

    public void setImpId(Long impId) {
        this.impId = impId;
    }

    public Long getImpSeq() {
        return this.impSeq;
    }

    public void setImpSeq(Long impSeq) {
        this.impSeq = impSeq;
    }

    public Date getImpDate() {
        return this.impDate;
    }

    public void setImpDate(Date impDate) {
        this.impDate = impDate;
    }

    public String getBankCode() {
        return this.bankCode;
    }

    public void setBankCode(String bankCode) {
        this.bankCode = bankCode;
    }

    public String getBankAbbr() {
        return this.bankAbbr;
    }

    public void setBankAbbr(String bankAbbr) {
        this.bankAbbr = bankAbbr;
    }

    public String getCompanyAccount() {
        return this.companyAccount;
    }

    public void setCompanyAccount(String companyAccount) {
        this.companyAccount = companyAccount;
    }

    public Date getPaymentDate() {
        return this.paymentDate;
    }

    public void setPaymentDate(Date paymentDate) {
        this.paymentDate = paymentDate;
    }

    public String getPaymentTime() {
        return this.paymentTime;
    }

    public void setPaymentTime(String paymentTime) {
        this.paymentTime = paymentTime;
    }

    public String getCustomerName() {
        return this.customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    public Long getPaymentNo() {
        return paymentNo;
    }

    public void setPaymentNo(Long paymentNo) {
        this.paymentNo = paymentNo;
    }

    public String getTellerNo() {
        return this.tellerNo;
    }

    public void setTellerNo(String tellerNo) {
        this.tellerNo = tellerNo;
    }

    public String getKindTrans() {
        return this.kindTrans;
    }

    public void setKindTrans(String kindTrans) {
        this.kindTrans = kindTrans;
    }

    public String getTransCode() {
        return this.transCode;
    }

    public void setTransCode(String transCode) {
        this.transCode = transCode;
    }

    public Long getChequeNo() {
        return this.chequeNo;
    }

    public void setChequeNo(Long chequeNo) {
        this.chequeNo = chequeNo;
    }

    public BigDecimal getPaymentAmount() {
        return this.paymentAmount;
    }

    public void setPaymentAmount(BigDecimal paymentAmount) {
        this.paymentAmount = paymentAmount;
    }

    public BigDecimal getTotalAmount() {
        return this.totalAmount;
    }

    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    public String getTransFlag() {
        return transFlag;
    }

    public void setTransFlag(String transFlag) {
        this.transFlag = transFlag;
    }

    public String getReceiptNo() {
        return this.receiptNo;
    }

    public void setReceiptNo(String receiptNo) {
        this.receiptNo = receiptNo;
    }

    public Date getReceiptDate() {
        return this.receiptDate;
    }

    public void setReceiptDate(Date receiptDate) {
        this.receiptDate = receiptDate;
    }

    public CtstScan getReceiptScanId() {
        return receiptScanId;
    }

    public void setReceiptScanId(CtstScan receiptScanId) {
        this.receiptScanId = receiptScanId;
    }

    public SistPaymentint getSistPaymentint() {
        return sistPaymentint;
    }

    public void setSistPaymentint(SistPaymentint sistPaymentint) {
        this.sistPaymentint = sistPaymentint;
    }

    public SistPaymentintDet getSistPaymentintDet() {
        return sistPaymentintDet;
    }

    public void setSistPaymentintDet(SistPaymentintDet sistPaymentintDet) {
        this.sistPaymentintDet = sistPaymentintDet;
    }

    public String getReceiptBook() {
        return this.receiptBook;
    }

    public void setReceiptBook(String receiptBook) {
        this.receiptBook = receiptBook;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 41 * hash + Objects.hashCode(this.impId);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final SistBankImport other = (SistBankImport) obj;
        if (!Objects.equals(this.impId, other.impId)) {
            return false;
        }
        return true;
    }

}
