package th.co.geniustree.trademark.ocr.domain;

// Generated Jan 29, 2014 4:37:08 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.time.LocalDate;
import java.util.Objects;

/**
 * SistNo02Trno generated by hbm2java
 */
@Entity
@Table(name = "SIST_NO02_TRNO")
public class SistNo02Trno extends BaseEntity implements java.io.Serializable {

    private static final long serialVersionUID = -2504266034606447292L;

    @Id
    @SequenceGenerator(name = "SIST_NO02_TRNO_SEQ", sequenceName = "SIST_NO02_TRNO_SEQ", initialValue = 1, allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SIST_NO02_TRNO_SEQ")
    @Column(name = "TRNO_ID", unique = true, nullable = false, precision = 15, scale = 0)
    private Long trnoId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TR_NO02_ID", nullable = false)
    private SistNo02 sistNo02;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TR_ID", nullable = false)
    private RpstTrademark rpstTrademark;

    @Column(name = "TR_DATE", length = 7)
    private LocalDate trDate;

    @Column(name = "TR_OWNER")
    private String trOwner;

    @Column(name = "TR_NO", precision = 15, scale = 0)
    private Long trNo;

    public SistNo02Trno() {
    }

    public SistNo02Trno(Long trnoId, SistNo02 sistNo02, RpstTrademark rpstTrademark) {
        this.trnoId = trnoId;
        this.sistNo02 = sistNo02;
        this.rpstTrademark = rpstTrademark;
    }

    @Transient
    public Long getPk() {
        return trnoId;
    }

    public Long getTrnoId() {
        return this.trnoId;
    }

    public void setTrnoId(Long trnoId) {
        this.trnoId = trnoId;
    }

    public SistNo02 getSistNo02() {
        return this.sistNo02;
    }

    public void setSistNo02(SistNo02 sistNo02) {
        this.sistNo02 = sistNo02;
    }

    public RpstTrademark getRpstTrademark() {
        return this.rpstTrademark;
    }

    public void setRpstTrademark(RpstTrademark rpstTrademark) {
        this.rpstTrademark = rpstTrademark;
    }

    public LocalDate getTrDate() {
        return this.trDate;
    }

    public void setTrDate(LocalDate trDate) {
        this.trDate = trDate;
    }

    public String getTrOwner() {
        return this.trOwner;
    }

    public void setTrOwner(String trOwner) {
        this.trOwner = trOwner;
    }

    public Long getTrNo() {
        return this.trNo;
    }

    public void setTrNo(Long trNo) {
        this.trNo = trNo;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 79 * hash + Objects.hashCode(this.trnoId);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final SistNo02Trno other = (SistNo02Trno) obj;
        if (!Objects.equals(this.trnoId, other.trnoId)) {
            return false;
        }
        return true;
    }

}
