package th.co.geniustree.trademark.ocr.domain;

// default package
// Generated Oct 30, 2014 6:52:59 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.*;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.Objects;

/**
 * SistListPayment generated by hbm2java
 */
@Entity
@Table(name = "SIST_LIST_PAYMENT")
public class SistListPayment extends BaseEntity implements Serializable {

    private static final long serialVersionUID = 7727493558857952589L;

    @Id
    @SequenceGenerator(name = "SIST_LIST_PAYMENT_SEQ", sequenceName = "SIST_LIST_PAYMENT_SEQ", initialValue = 1, allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SIST_LIST_PAYMENT_SEQ")
    @Column(name = "LIST_PAY_ID", unique = true, nullable = false, precision = 15, scale = 0)
    private Long listPayId;

    @Column(name = "PAY_REF_NO", precision = 15, scale = 0)
    private Long payRefNo;

    @Temporal(TemporalType.DATE)
    @Column(name = "REQ_DATE", length = 7)
    private Date reqDate;

    @Column(name = "REQ_NAME", length = 500)
    private String reqName;

    @Column(name = "TR_NO", precision = 15, scale = 0)
    private Long trNo;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "BOOK_M_ID")
    private RpstBookM rpstBookM;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ORDER_ID")
    private NistOrder nistOrder;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "FEE_ID")
    private CtltFee ctltFee;

    @Column(name = "FEE_CODE", length = 3)
    private String feeCode;

    @Column(name = "FEE_AMOUNT", precision = 15)
    private BigDecimal feeAmount;

    @Column(name = "RECEIPT_NO", length = 10)
    private String receiptNo;

    @Column(name = "RECEIPT_BOOK", length = 10)
    private String receiptBook;

    @Temporal(TemporalType.DATE)
    @Column(name = "RECEIPT_DATE", length = 7)
    private Date receiptDate;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "RECEIPT_SCAN_ID")
    private CtstScan ctstScan;

    @Column(name = "UPDATE_BY_PRG", length = 20)
    private String updateByPrg;

    public SistListPayment() {
    }

    public SistListPayment(Long listPayId) {
        this.listPayId = listPayId;
    }

    @Transient
    public Long getPk() {
        return listPayId;
    }

    public Long getListPayId() {
        return this.listPayId;
    }

    public void setListPayId(Long listPayId) {
        this.listPayId = listPayId;
    }

    public Long getPayRefNo() {
        return this.payRefNo;
    }

    public void setPayRefNo(Long payRefNo) {
        this.payRefNo = payRefNo;
    }

    public Date getReqDate() {
        return this.reqDate;
    }

    public void setReqDate(Date reqDate) {
        this.reqDate = reqDate;
    }

    public String getReqName() {
        return this.reqName;
    }

    public void setReqName(String reqName) {
        this.reqName = reqName;
    }

    public Long getTrNo() {
        return this.trNo;
    }

    public void setTrNo(Long trNo) {
        this.trNo = trNo;
    }

    public RpstBookM getRpstBookM() {
        return rpstBookM;
    }

    public void setRpstBookM(RpstBookM rpstBookM) {
        this.rpstBookM = rpstBookM;
    }

    public NistOrder getNistOrder() {
        return nistOrder;
    }

    public void setNistOrder(NistOrder nistOrder) {
        this.nistOrder = nistOrder;
    }

    public CtltFee getCtltFee() {
        return ctltFee;
    }

    public void setCtltFee(CtltFee ctltFee) {
        this.ctltFee = ctltFee;
    }

    public String getFeeCode() {
        return this.feeCode;
    }

    public void setFeeCode(String feeCode) {
        this.feeCode = feeCode;
    }

    public BigDecimal getFeeAmount() {
        return this.feeAmount;
    }

    public void setFeeAmount(BigDecimal feeAmount) {
        this.feeAmount = feeAmount;
    }

    public String getReceiptNo() {
        return this.receiptNo;
    }

    public void setReceiptNo(String receiptNo) {
        this.receiptNo = receiptNo;
    }

    public String getReceiptBook() {
        return receiptBook;
    }

    public void setReceiptBook(String receiptBook) {
        this.receiptBook = receiptBook;
    }

    public Date getReceiptDate() {
        return this.receiptDate;
    }

    public void setReceiptDate(Date receiptDate) {
        this.receiptDate = receiptDate;
    }

    public CtstScan getCtstScan() {
        return ctstScan;
    }

    public void setCtstScan(CtstScan ctstScan) {
        this.ctstScan = ctstScan;
    }

    public String getUpdateByPrg() {
        return this.updateByPrg;
    }

    public void setUpdateByPrg(String updateByPrg) {
        this.updateByPrg = updateByPrg;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 19 * hash + Objects.hashCode(this.listPayId);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final SistListPayment other = (SistListPayment) obj;
        if (!Objects.equals(this.listPayId, other.listPayId)) {
            return false;
        }
        return true;
    }

}
