package th.co.geniustree.trademark.ocr.domain;

// default package
// Generated Jul 7, 2014 3:51:11 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.*;
import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Date;
import java.util.Objects;

/**
 * SistNo01 generated by hbm2java
 */
@Entity
@Table(name = "SIST_NO01")
public class SistNo01 extends BaseEntity implements Serializable {


    private static final long serialVersionUID = 4208173961788019340L;

    @Id
    @SequenceGenerator(name = "SIST_NO01_SEQ", sequenceName = "SIST_NO01_SEQ", initialValue = 1, allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SIST_NO01_SEQ")
    @Column(name = "TR_NO01_ID", unique = true, nullable = false, precision = 22, scale = 0)
    private Long trNo01Id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CONT_COUNTRY_ID")
    private CtltCountry contCtltCountry;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CONT_LOC_ID")
    private CtltLocation ctltLocation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "COUNTRY_ID")
    private CtltCountry ctltCountry;

    @Column(name = "TR_NO", precision = 13, scale = 0)
    private Long trNo;

    @Column(name = "TR_DATE", length = 7)
    private LocalDate trDate;

    @Column(name = "TR_TYPE", length = 1)
    private String trType;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "COM_ORG_ID")
    private CtltOrganize compCtltOrganize;

    @Column(name = "THREE_D_FLAG", length = 1)
    private String threeDFlag;

    @Column(name = "COLOURGRP_FLAG", length = 1)
    private String colourgrpFlag;

    @Column(name = "SOUND_FLAG", length = 1)
    private String soundFlag;

    @Column(name = "SCENT_FLAG", length = 1)
    private String scentFlag;

    @Column(name = "PAY_FLAG", length = 1)
    private String payFlag;

    @Column(name = "FEE_AMOUNT", precision = 10)
    private BigDecimal feeAmount;

    @Temporal(TemporalType.DATE)
    @Column(name = "RECV_DATE", length = 7)
    private Date recvDate;

    @Column(name = "CONT_NAME", length = 150)
    private String contName;

    @Column(name = "CONT_TO", length = 1)
    private String contTo;

    @Column(name = "CONT_TO_DET")
    private String contToDet;

    @Column(name = "CONT_TYPE", length = 1)
    private String contType;

    @Column(name = "CONT_TYPE_DET")
    private String contTypeDet;

    @Column(name = "CONT_CARD_TYPE", length = 1)
    private String contCardType;

    @Column(name = "CONT_CARD_NO", length = 25)
    private String contCardNo;

    @Column(name = "CONT_GENDER", length = 1)
    private String contGender;

    @Column(name = "CONT_ADDR", length = 1000)
    private String contAddr;

    @Column(name = "CONT_LOC_CODE", length = 8)
    private String contLocCode;

    @Column(name = "CONT_POSTCODE", length = 8)
    private String contPostcode;

    @Column(name = "CONT_PHONE", length = 150)
    private String contPhone;

    @Column(name = "CONT_FAX", length = 150)
    private String contFax;

    @Column(name = "CONT_EMAIL", length = 150)
    private String contEmail;

    @Column(name = "INTERNET_FLAG", length = 1)
    private String internetFlag;

    @Temporal(TemporalType.DATE)
    @Column(name = "INTERNET_DATE", length = 7)
    private Date internetDate;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TRW_NO01_ID")
    private TrwtNo01 trwtNo01;

    @Column(name = "OTOP_TYPE", length = 1)
    private String otopType;

    @Column(name = "OTOP_NO", length = 20)
    private String otopNo;

    @Column(name = "RULE_DESC", length = 1000)
    private String ruleDesc;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "RECV_ID")
    private SistRecvTm sistRecvTm;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "JOB_ID")
    private CtltRecvJob ctltRecvJob;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SCAN_ID")
    private CtstScan ctstScan;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TR_ID")
    private RpstTrademark rpstTrademark;

    @Column(name = "SEND_FLAG", length = 1)
    private String sendFlag;

    @Column(name = "EVIDENCE_PLACE", length = 150)
    private String evidencePlace;

    @Column(name = "IB_MADRID_NO", length = 50)
    private String ibMadridNo;

    /*Add for Madrid*/
    @Column(name = "IS_CONVERN_FLAG", length = 1)
    private Boolean isConvernFlag;


    public SistNo01() {
    }

    public SistNo01(Long trNo01Id) {
        this.trNo01Id = trNo01Id;
    }

    @Transient
    public Long getPk() {
        return trNo01Id;
    }


    public Long getTrNo01Id() {
        return this.trNo01Id;
    }

    public void setTrNo01Id(Long trNo01Id) {
        this.trNo01Id = trNo01Id;
    }

    public CtltCountry getContCtltCountry() {
        return contCtltCountry;
    }

    public void setContCtltCountry(CtltCountry contCtltCountry) {
        this.contCtltCountry = contCtltCountry;
    }

    public CtltLocation getCtltLocation() {
        return this.ctltLocation;
    }

    public void setCtltLocation(CtltLocation ctltLocation) {
        this.ctltLocation = ctltLocation;
    }

    public CtltCountry getCtltCountry() {
        return ctltCountry;
    }

    public void setCtltCountry(CtltCountry ctltCountry) {
        this.ctltCountry = ctltCountry;
    }

    public Long getTrNo() {
        return this.trNo;
    }

    public void setTrNo(Long trNo) {
        this.trNo = trNo;
    }

    public LocalDate getTrDate() {
        return trDate;
    }

    public void setTrDate(LocalDate trDate) {
        this.trDate = trDate;
    }

    public String getTrType() {
        return this.trType;
    }

    public void setTrType(String trType) {
        this.trType = trType;
    }

    public CtltOrganize getCompCtltOrganize() {
        return compCtltOrganize;
    }

    public void setCompCtltOrganize(CtltOrganize compCtltOrganize) {
        this.compCtltOrganize = compCtltOrganize;
    }

    public String getThreeDFlag() {
        return this.threeDFlag;
    }

    public void setThreeDFlag(String threeDFlag) {
        this.threeDFlag = threeDFlag;
    }

    public String getColourgrpFlag() {
        return this.colourgrpFlag;
    }

    public void setColourgrpFlag(String colourgrpFlag) {
        this.colourgrpFlag = colourgrpFlag;
    }

    public String getSoundFlag() {
        return this.soundFlag;
    }

    public void setSoundFlag(String soundFlag) {
        this.soundFlag = soundFlag;
    }

    public String getScentFlag() {
        return this.scentFlag;
    }

    public void setScentFlag(String scentFlag) {
        this.scentFlag = scentFlag;
    }

    public String getPayFlag() {
        return this.payFlag;
    }

    public void setPayFlag(String payFlag) {
        this.payFlag = payFlag;
    }

    public BigDecimal getFeeAmount() {
        return this.feeAmount;
    }

    public void setFeeAmount(BigDecimal feeAmount) {
        this.feeAmount = feeAmount;
    }

    public Date getRecvDate() {
        return this.recvDate;
    }

    public void setRecvDate(Date recvDate) {
        this.recvDate = recvDate;
    }

    public String getContName() {
        return this.contName;
    }

    public void setContName(String contName) {
        this.contName = contName;
    }

    public String getContTo() {
        return this.contTo;
    }

    public void setContTo(String contTo) {
        this.contTo = contTo;
    }

    public String getContToDet() {
        return this.contToDet;
    }

    public void setContToDet(String contToDet) {
        this.contToDet = contToDet;
    }

    public String getContType() {
        return this.contType;
    }

    public void setContType(String contType) {
        this.contType = contType;
    }

    public String getContTypeDet() {
        return this.contTypeDet;
    }

    public void setContTypeDet(String contTypeDet) {
        this.contTypeDet = contTypeDet;
    }

    public String getContCardType() {
        return this.contCardType;
    }

    public void setContCardType(String contCardType) {
        this.contCardType = contCardType;
    }

    public String getContCardNo() {
        return this.contCardNo;
    }

    public void setContCardNo(String contCardNo) {
        this.contCardNo = contCardNo;
    }

    public String getContGender() {
        return this.contGender;
    }

    public void setContGender(String contGender) {
        this.contGender = contGender;
    }

    public String getContAddr() {
        return this.contAddr;
    }

    public void setContAddr(String contAddr) {
        this.contAddr = contAddr;
    }

    public String getContLocCode() {
        return this.contLocCode;
    }

    public void setContLocCode(String contLocCode) {
        this.contLocCode = contLocCode;
    }

    public String getContPostcode() {
        return this.contPostcode;
    }

    public void setContPostcode(String contPostcode) {
        this.contPostcode = contPostcode;
    }

    public String getContPhone() {
        return this.contPhone;
    }

    public void setContPhone(String contPhone) {
        this.contPhone = contPhone;
    }

    public String getContFax() {
        return this.contFax;
    }

    public void setContFax(String contFax) {
        this.contFax = contFax;
    }

    public String getContEmail() {
        return this.contEmail;
    }

    public void setContEmail(String contEmail) {
        this.contEmail = contEmail;
    }

    public String getInternetFlag() {
        return this.internetFlag;
    }

    public void setInternetFlag(String internetFlag) {
        this.internetFlag = internetFlag;
    }

    public Date getInternetDate() {
        return this.internetDate;
    }

    public void setInternetDate(Date internetDate) {
        this.internetDate = internetDate;
    }

    public TrwtNo01 getTrwtNo01() {
        return trwtNo01;
    }

    public void setTrwtNo01(TrwtNo01 trwtNo01) {
        this.trwtNo01 = trwtNo01;
    }

    public String getOtopType() {
        return otopType;
    }

    public void setOtopType(String otopType) {
        this.otopType = otopType;
    }

    public String getOtopNo() {
        return this.otopNo;
    }

    public void setOtopNo(String otopNo) {
        this.otopNo = otopNo;
    }

    public String getRuleDesc() {
        return this.ruleDesc;
    }

    public void setRuleDesc(String ruleDesc) {
        this.ruleDesc = ruleDesc;
    }

    public SistRecvTm getSistRecvTm() {
        return sistRecvTm;
    }

    public void setSistRecvTm(SistRecvTm sistRecvTm) {
        this.sistRecvTm = sistRecvTm;
    }

    public CtltRecvJob getCtltRecvJob() {
        return ctltRecvJob;
    }

    public void setCtltRecvJob(CtltRecvJob ctltRecvJob) {
        this.ctltRecvJob = ctltRecvJob;
    }

    public CtstScan getCtstScan() {
        return ctstScan;
    }

    public void setCtstScan(CtstScan ctstScan) {
        this.ctstScan = ctstScan;
    }

    public RpstTrademark getRpstTrademark() {
        return rpstTrademark;
    }

    public void setRpstTrademark(RpstTrademark rpstTrademark) {
        this.rpstTrademark = rpstTrademark;
    }

    public String getSendFlag() {
        return sendFlag;
    }

    public void setSendFlag(String sendFlag) {
        this.sendFlag = sendFlag;
    }

    public String getEvidencePlace() {
        return evidencePlace;
    }

    public void setEvidencePlace(String evidencePlace) {
        this.evidencePlace = evidencePlace;
    }

    public String getIbMadridNo() {
        return ibMadridNo;
    }

    public void setIbMadridNo(String ibMadridNo) {
        this.ibMadridNo = ibMadridNo;
    }

    public Boolean getConvernFlag() {
        return isConvernFlag;
    }

    public void setConvernFlag(Boolean convernFlag) {
        isConvernFlag = convernFlag;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 37 * hash + Objects.hashCode(this.trNo01Id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final SistNo01 other = (SistNo01) obj;
        if (!Objects.equals(this.trNo01Id, other.trNo01Id)) {
            return false;
        }
        return true;
    }

}
