package th.co.geniustree.trademark.ocr.domain;

// Generated Feb 17, 2014 11:11:14 AM by Hibernate Tools 3.4.0.CR1



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Date;
import java.util.Objects;

/**
 * SistNo03 generated by hbm2java
 */
@Entity
@Table(name = "SIST_NO03")
public class SistNo03 extends BaseEntity implements java.io.Serializable {

    private static final long serialVersionUID = 1772272439054317920L;

    @Id
    @SequenceGenerator(name = "SIST_NO03_SEQ", sequenceName = "SIST_NO03_SEQ", initialValue = 1, allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SIST_NO03_SEQ")
    @Column(name = "TR_NO03_ID", unique = true, nullable = false, precision = 15, scale = 0)
    private Long trNo03Id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TR_ID")
    private RpstTrademark rpstTrademark;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "COM_ORG_ID")
    private CtltOrganize ctltOrganize;


    @Column(name = "TR_NO03_DATE", length = 7)
    private LocalDate trNo03Date;

    @Column(name = "TR_NO03_SEQ", precision = 10)
    private BigDecimal trNo03Seq;

    @Column(name = "TR_NO", precision = 15, scale = 0)
    private Long trNo;

    @Column(name = "TR_DATE", length = 7)
    private LocalDate trDate;

    @Column(name = "PAY_FLAG", length = 1)
    private String payFlag;

    @Column(name = "FEE_AMOUNT", precision = 10)
    private BigDecimal feeAmount;

    @Column(name = "APPL_TYPE", length = 1)
    private String applType;

    @Column(name = "APPL_DESC")
    private String applDesc;

    @Column(name = "REQ_TYPE", length = 1)
    private String reqType;

    @Column(name = "REMARK", length = 1000)
    private String remark;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "RECV_ID")
    private SistRecvTm sistRecvTm;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "JOB_ID")
    private CtltRecvJob ctltRecvJob;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SCAN_ID")
    private CtstScan ctstScan;

    @Column(name = "SEND_FLAG", length = 1)
    private String sendFlag;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TRW_NO03_ID")
    private TrwtNo03 trwtNo03;

    @Column(name = "GIST_GRP", length = 1)
    private String gistGrp;

    @Column(name = "CONT_NAME", length = 150)
    private String contName;

    @Column(name = "CONT_TO", length = 1)
    private String contTo;

    @Column(name = "CONT_TO_DET")
    private String contToDet;

    @Column(name = "CONT_TYPE", length = 1)
    private String contType;

    @Column(name = "CONT_TYPE_DET")
    private String contTypeDet;

    @Column(name = "CONT_CARD_TYPE", length = 1)
    private String contCardType;

    @Column(name = "CONT_CARD_NO", length = 25)
    private String contCardNo;

    @Column(name = "CONT_GENDER", length = 1)
    private String contGender;

    @Column(name = "CONT_ADDR", length = 1000)
    private String contAddr;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CONT_LOC_ID")
    private CtltLocation ctltLocation;

    @Column(name = "CONT_LOC_CODE", length = 8)
    private String contLocCode;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CONT_COUNTRY_ID")
    private CtltCountry ctltCountry;

    @Column(name = "CONT_POSTCODE", length = 8)
    private String contPostcode;

    @Column(name = "CONT_PHONE", length = 150)
    private String contPhone;

    @Column(name = "CONT_FAX", length = 150)
    private String contFax;

    @Column(name = "CONT_EMAIL", length = 150)
    private String contEmail;

    @Column(name = "TR_NO03_YEAR", length = 4)
    private String trNo03Year;

    @Column(name = "IN_FILE", length = 1)
    private String inFile;

    public SistNo03() {
    }

    public SistNo03(Long trNo03Id) {
        this.trNo03Id = trNo03Id;
    }

    @Transient
    public Long getPk() {
        return trNo03Id;
    }

    public Long getTrNo03Id() {
        return this.trNo03Id;
    }

    public void setTrNo03Id(Long trNo03Id) {
        this.trNo03Id = trNo03Id;
    }

    public RpstTrademark getRpstTrademark() {
        return this.rpstTrademark;
    }

    public void setRpstTrademark(RpstTrademark rpstTrademark) {
        this.rpstTrademark = rpstTrademark;
    }

    public CtltOrganize getCtltOrganize() {
        return this.ctltOrganize;
    }

    public void setCtltOrganize(CtltOrganize ctltOrganize) {
        this.ctltOrganize = ctltOrganize;
    }

    public LocalDate getTrNo03Date() {
        return this.trNo03Date;
    }

    public void setTrNo03Date(LocalDate trNo03Date) {
        this.trNo03Date = trNo03Date;
    }

    public BigDecimal getTrNo03Seq() {
        return this.trNo03Seq;
    }

    public void setTrNo03Seq(BigDecimal trNo03Seq) {
        this.trNo03Seq = trNo03Seq;
    }

    public Long getTrNo() {
        return this.trNo;
    }

    public void setTrNo(Long trNo) {
        this.trNo = trNo;
    }

    public LocalDate getTrDate() {
        return this.trDate;
    }

    public void setTrDate(LocalDate trDate) {
        this.trDate = trDate;
    }

    public String getPayFlag() {
        return this.payFlag;
    }

    public void setPayFlag(String payFlag) {
        this.payFlag = payFlag;
    }

    public BigDecimal getFeeAmount() {
        return this.feeAmount;
    }

    public void setFeeAmount(BigDecimal feeAmount) {
        this.feeAmount = feeAmount;
    }

    public String getApplType() {
        return this.applType;
    }

    public void setApplType(String applType) {
        this.applType = applType;
    }

    public String getApplDesc() {
        return this.applDesc;
    }

    public void setApplDesc(String applDesc) {
        this.applDesc = applDesc;
    }

    public String getReqType() {
        return this.reqType;
    }

    public void setReqType(String reqType) {
        this.reqType = reqType;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public SistRecvTm getSistRecvTm() {
        return sistRecvTm;
    }

    public void setSistRecvTm(SistRecvTm sistRecvTm) {
        this.sistRecvTm = sistRecvTm;
    }

    public CtltRecvJob getCtltRecvJob() {
        return ctltRecvJob;
    }

    public void setCtltRecvJob(CtltRecvJob ctltRecvJob) {
        this.ctltRecvJob = ctltRecvJob;
    }

    public CtstScan getCtstScan() {
        return ctstScan;
    }

    public void setCtstScan(CtstScan ctstScan) {
        this.ctstScan = ctstScan;
    }

    public String getSendFlag() {
        return sendFlag;
    }

    public void setSendFlag(String sendFlag) {
        this.sendFlag = sendFlag;
    }

    public TrwtNo03 getTrwtNo03() {
        return trwtNo03;
    }

    public void setTrwtNo03(TrwtNo03 trwtNo03) {
        this.trwtNo03 = trwtNo03;
    }

    public String getGistGrp() {
        return gistGrp;
    }

    public void setGistGrp(String gistGrp) {
        this.gistGrp = gistGrp;
    }

    public String getContName() {
        return this.contName;
    }

    public void setContName(String contName) {
        this.contName = contName;
    }

    public String getContTo() {
        return this.contTo;
    }

    public void setContTo(String contTo) {
        this.contTo = contTo;
    }

    public String getContToDet() {
        return this.contToDet;
    }

    public void setContToDet(String contToDet) {
        this.contToDet = contToDet;
    }

    public String getContType() {
        return this.contType;
    }

    public void setContType(String contType) {
        this.contType = contType;
    }

    public String getContTypeDet() {
        return this.contTypeDet;
    }

    public void setContTypeDet(String contTypeDet) {
        this.contTypeDet = contTypeDet;
    }

    public String getContCardType() {
        return this.contCardType;
    }

    public void setContCardType(String contCardType) {
        this.contCardType = contCardType;
    }

    public String getContCardNo() {
        return this.contCardNo;
    }

    public void setContCardNo(String contCardNo) {
        this.contCardNo = contCardNo;
    }

    public String getContGender() {
        return this.contGender;
    }

    public void setContGender(String contGender) {
        this.contGender = contGender;
    }

    public String getContAddr() {
        return this.contAddr;
    }

    public void setContAddr(String contAddr) {
        this.contAddr = contAddr;
    }

    public CtltLocation getCtltLocation() {
        return ctltLocation;
    }

    public void setCtltLocation(CtltLocation ctltLocation) {
        this.ctltLocation = ctltLocation;
    }

    public String getContLocCode() {
        return this.contLocCode;
    }

    public void setContLocCode(String contLocCode) {
        this.contLocCode = contLocCode;
    }

    public CtltCountry getCtltCountry() {
        return ctltCountry;
    }

    public void setCtltCountry(CtltCountry ctltCountry) {
        this.ctltCountry = ctltCountry;
    }

    public String getContPostcode() {
        return this.contPostcode;
    }

    public void setContPostcode(String contPostcode) {
        this.contPostcode = contPostcode;
    }

    public String getContPhone() {
        return this.contPhone;
    }

    public void setContPhone(String contPhone) {
        this.contPhone = contPhone;
    }

    public String getContFax() {
        return this.contFax;
    }

    public void setContFax(String contFax) {
        this.contFax = contFax;
    }

    public String getContEmail() {
        return this.contEmail;
    }

    public void setContEmail(String contEmail) {
        this.contEmail = contEmail;
    }

    public String getTrNo03Year() {
        return trNo03Year;
    }

    public void setTrNo03Year(String trNo03Year) {
        this.trNo03Year = trNo03Year;
    }

    public String getInFile() {
        return inFile;
    }

    public void setInFile(String inFile) {
        this.inFile = inFile;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 53 * hash + Objects.hashCode(this.trNo03Id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final SistNo03 other = (SistNo03) obj;
        if (!Objects.equals(this.trNo03Id, other.trNo03Id)) {
            return false;
        }
        return true;
    }

}
