package th.co.geniustree.trademark.ocr.domain;

// default package
// Generated Jul 7, 2014 3:51:11 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.*;
import java.io.Serializable;
import java.util.Objects;

/**
 * SistNo01Owner generated by hbm2java
 */
@Entity
@Table(name = "SIST_NO01_OWNER")
public class SistNo01Owner extends BaseEntity implements Serializable {
    private static final long serialVersionUID = -3254967531142315436L;

    @Id
    @SequenceGenerator(name = "SIST_NO01_OWNER_SEQ", sequenceName = "SIST_NO01_OWNER_SEQ", initialValue = 1, allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SIST_NO01_OWNER_SEQ")
    @Column(name = "OWNER_ID", unique = true, nullable = false, precision = 15, scale = 0)
    private Long ownerId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "LOC_ID")
    private CtltLocation ctltLocation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "OCCU_ID")
    private CtltOccupation ctltOccupation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TR_NO01_ID", nullable = false)
    private SistNo01 sistNo01;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "NAT_ID")
    private CtltNation ctltNation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "COUNTRY_ID")
    private CtltCountry ctltCountry;

    @Column(name = "OWNER_TYPE", length = 1)
    private String ownerType;

    @Column(name = "OWNER_TYPE_DET")
    private String ownerTypeDet;

    @Column(name = "OWNER_CARD_NO", length = 50)
    private String ownerCardNo;

    @Column(name = "OWNER_CARD_TYPE", length = 1)
    private String ownerCardType;

    @Column(name = "OWNER_NAME", length = 255)
    private String ownerName;

    @Column(name = "OWNER_DET")
    private String ownerDet;

    @Column(name = "OWNER_GENDER", length = 1)
    private String ownerGender;

    @Column(name = "OWNER_ADDR", length = 1000)
    private String ownerAddr;

    @Column(name = "LOC_CODE", length = 8)
    private String locCode;

    @Column(name = "OWNER_POSTCODE", length = 10)
    private String ownerPostcode;

    @Column(name = "OWNER_PHONE", length = 50)
    private String ownerPhone;

    @Column(name = "OWNER_FAX", length = 50)
    private String ownerFax;

    @Column(name = "OWNER_EMAIL", length = 150)
    private String ownerEmail;

    @Column(name = "OWNER_SEQ", precision = 2, scale = 0)
    private Long ownerSeq;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TRW_OWNER_ID")
    private TrwtNo01Owner trwtNo01Owner;

    public SistNo01Owner() {
    }

    public SistNo01Owner(Long ownerId, SistNo01 sistNo01) {
        this.ownerId = ownerId;
        this.sistNo01 = sistNo01;
    }

    @Transient
    public Long getPk() {
        return ownerId;
    }

    public Long getOwnerId() {
        return this.ownerId;
    }

    public void setOwnerId(Long ownerId) {
        this.ownerId = ownerId;
    }

    public CtltLocation getCtltLocation() {
        return this.ctltLocation;
    }

    public void setCtltLocation(CtltLocation ctltLocation) {
        this.ctltLocation = ctltLocation;
    }

    public CtltOccupation getCtltOccupation() {
        return this.ctltOccupation;
    }

    public void setCtltOccupation(CtltOccupation ctltOccupation) {
        this.ctltOccupation = ctltOccupation;
    }

    public SistNo01 getSistNo01() {
        return this.sistNo01;
    }

    public void setSistNo01(SistNo01 sistNo01) {
        this.sistNo01 = sistNo01;
    }

    public CtltNation getCtltNation() {
        return this.ctltNation;
    }

    public void setCtltNation(CtltNation ctltNation) {
        this.ctltNation = ctltNation;
    }

    public CtltCountry getCtltCountry() {
        return this.ctltCountry;
    }

    public void setCtltCountry(CtltCountry ctltCountry) {
        this.ctltCountry = ctltCountry;
    }

    public String getOwnerType() {
        return this.ownerType;
    }

    public void setOwnerType(String ownerType) {
        this.ownerType = ownerType;
    }

    public String getOwnerTypeDet() {
        return this.ownerTypeDet;
    }

    public void setOwnerTypeDet(String ownerTypeDet) {
        this.ownerTypeDet = ownerTypeDet;
    }

    public String getOwnerCardNo() {
        return this.ownerCardNo;
    }

    public void setOwnerCardNo(String ownerCardNo) {
        this.ownerCardNo = ownerCardNo;
    }

    public String getOwnerCardType() {
        return this.ownerCardType;
    }

    public void setOwnerCardType(String ownerCardType) {
        this.ownerCardType = ownerCardType;
    }

    public String getOwnerName() {
        return this.ownerName;
    }

    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName;
    }

    public String getOwnerDet() {
        return this.ownerDet;
    }

    public void setOwnerDet(String ownerDet) {
        this.ownerDet = ownerDet;
    }

    public String getOwnerGender() {
        return this.ownerGender;
    }

    public void setOwnerGender(String ownerGender) {
        this.ownerGender = ownerGender;
    }

    public String getOwnerAddr() {
        return this.ownerAddr;
    }

    public void setOwnerAddr(String ownerAddr) {
        this.ownerAddr = ownerAddr;
    }

    public String getLocCode() {
        return this.locCode;
    }

    public void setLocCode(String locCode) {
        this.locCode = locCode;
    }

    public String getOwnerPostcode() {
        return this.ownerPostcode;
    }

    public void setOwnerPostcode(String ownerPostcode) {
        this.ownerPostcode = ownerPostcode;
    }

    public String getOwnerPhone() {
        return this.ownerPhone;
    }

    public void setOwnerPhone(String ownerPhone) {
        this.ownerPhone = ownerPhone;
    }

    public String getOwnerFax() {
        return this.ownerFax;
    }

    public void setOwnerFax(String ownerFax) {
        this.ownerFax = ownerFax;
    }

    public String getOwnerEmail() {
        return this.ownerEmail;
    }

    public void setOwnerEmail(String ownerEmail) {
        this.ownerEmail = ownerEmail;
    }

    public Long getOwnerSeq() {
        return this.ownerSeq;
    }

    public void setOwnerSeq(Long ownerSeq) {
        this.ownerSeq = ownerSeq;
    }

    public TrwtNo01Owner getTrwtNo01Owner() {
        return trwtNo01Owner;
    }

    public void setTrwtNo01Owner(TrwtNo01Owner trwtNo01Owner) {
        this.trwtNo01Owner = trwtNo01Owner;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 41 * hash + Objects.hashCode(this.ownerId);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final SistNo01Owner other = (SistNo01Owner) obj;
        if (!Objects.equals(this.ownerId, other.ownerId)) {
            return false;
        }
        return true;
    }


}
