package th.co.geniustree.trademark.ocr.domain;

// Generated Feb 25, 2014 8:57:01 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.Objects;

/**
 * SistNo05Permit generated by hbm2java
 */
@Entity
@Table(name = "SIST_NO05_PERMIT")
public class SistNo05Permit extends BaseEntity implements java.io.Serializable {

    private static final long serialVersionUID = 1743809025178131189L;

    @Id
    @SequenceGenerator(name = "SIST_NO05_PERMIT_SEQ", sequenceName = "SIST_NO05_PERMIT_SEQ", initialValue = 1, allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SIST_NO05_PERMIT_SEQ")
    @Column(name = "PERMIT_ID", unique = true, nullable = false, precision = 15, scale = 0)
    private Long permitId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "LOC_ID")
    private CtltLocation ctltLocation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "OCCU_ID")
    private CtltOccupation ctltOccupation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TR_NO05_ID", nullable = false)
    private SistNo05 sistNo05;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "NAT_ID")
    private CtltNation ctltNation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "COUNTRY_ID")
    private CtltCountry ctltCountry;

    @Column(name = "PERMIT_TYPE", length = 1)
    private String permitType;

    @Column(name = "PERMIT_TYPE_DET")
    private String permitTypeDet;

    @Column(name = "PERMIT_CARD_NO", length = 50)
    private String permitCardNo;

    @Column(name = "PERMIT_CARD_TYPE", length = 1)
    private String permitCardType;

    @Column(name = "PERMIT_NAME", length = 150)
    private String permitName;

    @Column(name = "PERMIT_DET")
    private String permitDet;

    @Column(name = "PERMIT_GENDER", length = 1)
    private String permitGender;

    @Column(name = "PERMIT_ADDR", length = 1000)
    private String permitAddr;

    @Column(name = "LOC_CODE", length = 8)
    private String locCode;

    @Column(name = "PERMIT_POSTCODE", length = 10)
    private String permitPostcode;

    @Column(name = "PERMIT_PHONE", length = 50)
    private String permitPhone;

    @Column(name = "PERMIT_FAX", length = 50)
    private String permitFax;

    @Column(name = "PERMIT_EMAIL", length = 150)
    private String permitEmail;

    @Column(name = "PERMIT_SEQ", precision = 1, scale = 0)
    private Long permitSeq;

    @Column(name = "PERMIT_KIND", precision = 1, scale = 0)
    private String permitKind;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TRW_JOWNER_ID")
    private TrwtNo05Jowner trwtNo05Jowner;

    public SistNo05Permit() {
    }

    public SistNo05Permit(Long permitId, SistNo05 sistNo05) {
        this.permitId = permitId;
        this.sistNo05 = sistNo05;
    }

    @Transient
    public Long getPk() {
        return permitId;
    }

    public Long getPermitId() {
        return this.permitId;
    }

    public void setPermitId(Long permitId) {
        this.permitId = permitId;
    }

    public CtltLocation getCtltLocation() {
        return this.ctltLocation;
    }

    public void setCtltLocation(CtltLocation ctltLocation) {
        this.ctltLocation = ctltLocation;
    }

    public CtltOccupation getCtltOccupation() {
        return this.ctltOccupation;
    }

    public void setCtltOccupation(CtltOccupation ctltOccupation) {
        this.ctltOccupation = ctltOccupation;
    }

    public SistNo05 getSistNo05() {
        return this.sistNo05;
    }

    public void setSistNo05(SistNo05 sistNo05) {
        this.sistNo05 = sistNo05;
    }

    public CtltNation getCtltNation() {
        return this.ctltNation;
    }

    public void setCtltNation(CtltNation ctltNation) {
        this.ctltNation = ctltNation;
    }

    public CtltCountry getCtltCountry() {
        return this.ctltCountry;
    }

    public void setCtltCountry(CtltCountry ctltCountry) {
        this.ctltCountry = ctltCountry;
    }

    public String getPermitType() {
        return this.permitType;
    }

    public void setPermitType(String permitType) {
        this.permitType = permitType;
    }

    public String getPermitTypeDet() {
        return this.permitTypeDet;
    }

    public void setPermitTypeDet(String permitTypeDet) {
        this.permitTypeDet = permitTypeDet;
    }

    public String getPermitCardNo() {
        return this.permitCardNo;
    }

    public void setPermitCardNo(String permitCardNo) {
        this.permitCardNo = permitCardNo;
    }

    public String getPermitCardType() {
        return this.permitCardType;
    }

    public void setPermitCardType(String permitCardType) {
        this.permitCardType = permitCardType;
    }

    public String getPermitName() {
        return this.permitName;
    }

    public void setPermitName(String permitName) {
        this.permitName = permitName;
    }

    public String getPermitDet() {
        return this.permitDet;
    }

    public void setPermitDet(String permitDet) {
        this.permitDet = permitDet;
    }

    public String getPermitGender() {
        return this.permitGender;
    }

    public void setPermitGender(String permitGender) {
        this.permitGender = permitGender;
    }

    public String getPermitAddr() {
        return this.permitAddr;
    }

    public void setPermitAddr(String permitAddr) {
        this.permitAddr = permitAddr;
    }

    public String getLocCode() {
        return this.locCode;
    }

    public void setLocCode(String locCode) {
        this.locCode = locCode;
    }

    public String getPermitPostcode() {
        return this.permitPostcode;
    }

    public void setPermitPostcode(String permitPostcode) {
        this.permitPostcode = permitPostcode;
    }

    public String getPermitPhone() {
        return this.permitPhone;
    }

    public void setPermitPhone(String permitPhone) {
        this.permitPhone = permitPhone;
    }

    public String getPermitFax() {
        return this.permitFax;
    }

    public void setPermitFax(String permitFax) {
        this.permitFax = permitFax;
    }

    public String getPermitEmail() {
        return this.permitEmail;
    }

    public void setPermitEmail(String permitEmail) {
        this.permitEmail = permitEmail;
    }

    public Long getPermitSeq() {
        return this.permitSeq;
    }

    public void setPermitSeq(Long permitSeq) {
        this.permitSeq = permitSeq;
    }

    public TrwtNo05Jowner getTrwtNo05Jowner() {
        return trwtNo05Jowner;
    }

    public void setTrwtNo05Jowner(TrwtNo05Jowner trwtNo05Jowner) {
        this.trwtNo05Jowner = trwtNo05Jowner;
    }

    public String getPermitKind() {
        return permitKind;
    }

    public void setPermitKind(String permitKind) {
        this.permitKind = permitKind;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 83 * hash + Objects.hashCode(this.permitId);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final SistNo05Permit other = (SistNo05Permit) obj;
        if (!Objects.equals(this.permitId, other.permitId)) {
            return false;
        }
        return true;
    }

}
