package th.co.geniustree.trademark.ocr.domain;

// Generated Dec 16, 2015 4:18:22 PM by Hibernate Tools 4.0.0


import javax.persistence.*;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.Objects;

/**
 * SistPaymentintDet generated by hbm2java
 */
@Entity
@Table(name = "SIST_PAYMENTINT_DET")
public class SistPaymentintDet extends BaseEntity implements Serializable {

    /**
     *
     */
    private static final long serialVersionUID = -2493402002848757614L;

    @Id
    @SequenceGenerator(name = "SIST_PAYMENTINT_DET_SEQ", sequenceName = "SIST_PAYMENTINT_DET_SEQ", initialValue = 1, allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SIST_PAYMENTINT_DET_SEQ")
    @Column(name = "PAYINT_DET_ID", unique = true, nullable = false, precision = 15, scale = 0)
    private Long payintDetId;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "PAYINT_ID")
    private SistPaymentint sistPaymentint;

    @Column(name = "FEE_AMOUNT", precision = 10)
    private BigDecimal feeAmount;

    @Column(name = "TR_NO", precision = 15, scale = 0)
    private Long trNo;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "SCAN_ID")
    private CtstScan ctstScan;

    @Column(name = "FILE_NAME", length = 150)
    private String fileName;

    @Temporal(TemporalType.DATE)
    @Column(name = "TR_DATE", length = 7)
    private Date trDate;

    @Column(name = "FEE_CODE", length = 3)
    private String feeCode;

    @Column(name = "RECEIPT_NO", length = 10)
    private String receiptNo;

    @Temporal(TemporalType.DATE)
    @Column(name = "RECEIPT_DATE", length = 7)
    private Date receiptDate;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "FEE_ID")
    private CtltFee ctltFee;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "REFNO_ID")
    private TrwtControlRefno trwtControlRefno;

    @Temporal(TemporalType.DATE)
    @Column(name = "CANCEL_DATE", length = 7)
    private Date cancelDate;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CANCEL_PERSON_ID")
    private CtltOfficer cancelCtltOfficer;

    @Column(name = "CANCEL_DESC")
    private String cancelDesc;

    @Column(name = "RECEIPT_BOOK", length = 10)
    private String receiptBook;

    @Column(name = "RETURN_FLAG", length = 1)
    private String returnFlag;

    @Column(name = "RETURN_DESC", length = 500)
    private String returnDesc;

    @Temporal(TemporalType.DATE)
    @Column(name = "RETURN_DATE", length = 7)
    private Date returnDate;

    @Column(name = "RETURN_PERSON_ID", precision = 22, scale = 0)
    private Long returnPersonId;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "RECV_ID")
    private SistRecvTm sistRecvTm;

    public SistPaymentintDet() {
    }

    public SistPaymentintDet(Long payintDetId) {
        this.payintDetId = payintDetId;
    }

    @Transient
    public Long getPk() {
        return payintDetId;
    }

    public Long getPayintDetId() {
        return this.payintDetId;
    }

    public void setPayintDetId(Long payintDetId) {
        this.payintDetId = payintDetId;
    }

    public SistPaymentint getSistPaymentint() {
        return sistPaymentint;
    }

    public void setSistPaymentint(SistPaymentint sistPaymentint) {
        this.sistPaymentint = sistPaymentint;
    }

    public BigDecimal getFeeAmount() {
        return this.feeAmount;
    }

    public void setFeeAmount(BigDecimal feeAmount) {
        this.feeAmount = feeAmount;
    }

    public Long getTrNo() {
        return this.trNo;
    }

    public void setTrNo(Long trNo) {
        this.trNo = trNo;
    }

    public CtstScan getCtstScan() {
        return ctstScan;
    }

    public void setCtstScan(CtstScan ctstScan) {
        this.ctstScan = ctstScan;
    }

    public String getFileName() {
        return this.fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public Date getTrDate() {
        return this.trDate;
    }

    public void setTrDate(Date trDate) {
        this.trDate = trDate;
    }

    public String getFeeCode() {
        return this.feeCode;
    }

    public void setFeeCode(String feeCode) {
        this.feeCode = feeCode;
    }

    public String getReceiptNo() {
        return this.receiptNo;
    }

    public void setReceiptNo(String receiptNo) {
        this.receiptNo = receiptNo;
    }

    public Date getReceiptDate() {
        return this.receiptDate;
    }

    public void setReceiptDate(Date receiptDate) {
        this.receiptDate = receiptDate;
    }

    public CtltFee getCtltFee() {
        return ctltFee;
    }

    public void setCtltFee(CtltFee ctltFee) {
        this.ctltFee = ctltFee;
    }

    public TrwtControlRefno getTrwtControlRefno() {
        return trwtControlRefno;
    }

    public void setTrwtControlRefno(TrwtControlRefno trwtControlRefno) {
        this.trwtControlRefno = trwtControlRefno;
    }

    public Date getCancelDate() {
        return this.cancelDate;
    }

    public void setCancelDate(Date cancelDate) {
        this.cancelDate = cancelDate;
    }

    public CtltOfficer getCancelCtltOfficer() {
        return cancelCtltOfficer;
    }

    public void setCancelCtltOfficer(CtltOfficer cancelCtltOfficer) {
        this.cancelCtltOfficer = cancelCtltOfficer;
    }

    public String getCancelDesc() {
        return this.cancelDesc;
    }

    public void setCancelDesc(String cancelDesc) {
        this.cancelDesc = cancelDesc;
    }

    public String getReceiptBook() {
        return this.receiptBook;
    }

    public void setReceiptBook(String receiptBook) {
        this.receiptBook = receiptBook;
    }

    public String getReturnFlag() {
        return this.returnFlag;
    }

    public void setReturnFlag(String returnFlag) {
        this.returnFlag = returnFlag;
    }

    public String getReturnDesc() {
        return this.returnDesc;
    }

    public void setReturnDesc(String returnDesc) {
        this.returnDesc = returnDesc;
    }

    public Date getReturnDate() {
        return this.returnDate;
    }

    public void setReturnDate(Date returnDate) {
        this.returnDate = returnDate;
    }

    public Long getReturnPersonId() {
        return this.returnPersonId;
    }

    public void setReturnPersonId(Long returnPersonId) {
        this.returnPersonId = returnPersonId;
    }

    public SistRecvTm getSistRecvTm() {
        return sistRecvTm;
    }

    public void setSistRecvTm(SistRecvTm sistRecvTm) {
        this.sistRecvTm = sistRecvTm;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 79 * hash + Objects.hashCode(this.payintDetId);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final SistPaymentintDet other = (SistPaymentintDet) obj;
        if (!Objects.equals(this.payintDetId, other.payintDetId)) {
            return false;
        }
        return true;
    }

}
