package th.co.geniustree.trademark.ocr.domain;


import javax.persistence.*;
import java.io.Serializable;
import java.util.Objects;

/**
 * TrwtNo05Goods generated by hbm2java
 */
@Entity
@Table(name = "TRWT_NO05_GOODS")
public class TrwtNo05Goods extends BaseEntity implements Serializable {

    private static final long serialVersionUID = -5156547642653303385L;

    @Id
    @SequenceGenerator(name = "TRWT_NO05_GOODS_SEQ", sequenceName = "TRWT_NO05_GOODS_SEQ", initialValue = 1, allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "TRWT_NO05_GOODS_SEQ")
    @Column(name = "GOODS_ID", unique = true, nullable = false, precision = 22, scale = 0)
    private Long goodsId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TRW_CLASS_ID")
    private TrwtNo05Class trwtNo05Class;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TRW_NO05_ID", nullable = false)
    private TrwtNo05 trwtNo05;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TR_GOODS_ID", nullable = false)
    private RpstTrGoods rpstTrGoods;

    @Column(name = "SEQ_NO", precision = 22, scale = 0)
    private Long seqNo;

    @Column(name = "GOODS_SERVICES", length = 4000)
    private String goodsServices;

    @Transient
    private String niceClassCode;

    public Long getGoodsId() {
        return this.goodsId;
    }

    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    public TrwtNo05Class getTrwtNo05Class() {
        return this.trwtNo05Class;
    }

    public void setTrwtNo05Class(TrwtNo05Class trwtNo05Class) {
        this.trwtNo05Class = trwtNo05Class;
    }

    public TrwtNo05 getTrwtNo05() {
        return this.trwtNo05;
    }

    public void setTrwtNo05(TrwtNo05 trwtNo05) {
        this.trwtNo05 = trwtNo05;
    }

    public RpstTrGoods getRpstTrGoods() {
        return this.rpstTrGoods;
    }

    public void setRpstTrGoods(RpstTrGoods rpstTrGoods) {
        this.rpstTrGoods = rpstTrGoods;
    }

    public Long getSeqNo() {
        return this.seqNo;
    }

    public void setSeqNo(Long seqNo) {
        this.seqNo = seqNo;
    }

    public String getGoodsServices() {
        return this.goodsServices;
    }

    public void setGoodsServices(String goodsServices) {
        this.goodsServices = goodsServices;
    }

    public String getNiceClassCode() {
        return niceClassCode;
    }

    public void setNiceClassCode(String niceClassCode) {
        this.niceClassCode = niceClassCode;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 37 * hash + Objects.hashCode(this.goodsId);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final TrwtNo05Goods other = (TrwtNo05Goods) obj;
        if (!Objects.equals(this.goodsId, other.goodsId)) {
            return false;
        }
        return true;
    }

}
