package th.co.geniustree.trademark.ocr.domain;

// Generated Jan 2, 2014 10:59:53 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.io.Serializable;
import java.util.Objects;

/**
 * TrwtNo04Agenass generated by hbm2java
 */
@Entity
@Table(name = "TRWT_NO04_AGENASS")
public class TrwtNo04Agenass extends BaseEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @SequenceGenerator(name = "TRWT_NO04_AGENASS_SEQ", sequenceName = "TRWT_NO04_AGENASS_SEQ", initialValue = 1, allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "TRWT_NO04_AGENASS_SEQ")
    @Column(name = "AGENASS_ID", unique = true, nullable = false, precision = 15, scale = 0)
    private Long agenassId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TITLE_ID")
    private CtltTitle ctltTitle;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "LOC_ID")
    private CtltLocation ctltLocation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "OCCU_ID")
    private CtltOccupation ctltOccupation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TRW_NO04_ID")
    private TrwtNo04 trwtNo04;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "NAT_ID")
    private CtltNation ctltNation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "COUNTRY_ID")
    private CtltCountry ctltCountry;

    @Column(name = "AGENASS_TYPE", length = 1)
    private String agenassType;

    @Column(name = "AGENASS_NAME", length = 150)
    private String agenassName;

    @Column(name = "AGENASS_SURNAME", length = 150)
    private String agenassSurname;

    @Column(name = "AGENASS_CARDID", length = 50)
    private String agenassCardid;

    @Column(name = "AGENASS_ADDR", length = 150)
    private String agenassAddr;

    @Column(name = "AGENASS_MOO", length = 150)
    private String agenassMoo;

    @Column(name = "AGENASS_SOI", length = 150)
    private String agenassSoi;

    @Column(name = "AGENASS_ROAD", length = 150)
    private String agenassRoad;

    @Column(name = "AGENASS_POSTCODE", length = 10)
    private String agenassPostcode;

    @Column(name = "AGENASS_PHONE", length = 50)
    private String agenassPhone;

    @Column(name = "AGENASS_FAX", length = 50)
    private String agenassFax;

    @Column(name = "AGENASS_EMAIL", length = 150)
    private String agenassEmail;

    @Column(name = "USE_STATUS", length = 1)
    private String useStatus;

    @Column(name = "AND_OR_TYPE", length = 1)
    private String andOrType;

    @Column(name = "AGEN_KIND", length = 1)
    private String agenKind;

    public Long getAgenassId() {
        return agenassId;
    }

    public void setAgenassId(Long agenassId) {
        this.agenassId = agenassId;
    }

    public CtltTitle getCtltTitle() {
        return ctltTitle;
    }

    public void setCtltTitle(CtltTitle ctltTitle) {
        this.ctltTitle = ctltTitle;
    }

    public CtltLocation getCtltLocation() {
        return ctltLocation;
    }

    public void setCtltLocation(CtltLocation ctltLocation) {
        this.ctltLocation = ctltLocation;
    }

    public CtltOccupation getCtltOccupation() {
        return ctltOccupation;
    }

    public void setCtltOccupation(CtltOccupation ctltOccupation) {
        this.ctltOccupation = ctltOccupation;
    }

    public TrwtNo04 getTrwtNo04() {
        return trwtNo04;
    }

    public void setTrwtNo04(TrwtNo04 trwtNo04) {
        this.trwtNo04 = trwtNo04;
    }

    public CtltNation getCtltNation() {
        return ctltNation;
    }

    public void setCtltNation(CtltNation ctltNation) {
        this.ctltNation = ctltNation;
    }

    public CtltCountry getCtltCountry() {
        return ctltCountry;
    }

    public void setCtltCountry(CtltCountry ctltCountry) {
        this.ctltCountry = ctltCountry;
    }

    public String getAgenassType() {
        return agenassType;
    }

    public void setAgenassType(String agenassType) {
        this.agenassType = agenassType;
    }

    public String getAgenassName() {
        return agenassName;
    }

    public void setAgenassName(String agenassName) {
        this.agenassName = agenassName;
    }

    public String getAgenassSurname() {
        return agenassSurname;
    }

    public void setAgenassSurname(String agenassSurname) {
        this.agenassSurname = agenassSurname;
    }

    public String getAgenassCardid() {
        return agenassCardid;
    }

    public void setAgenassCardid(String agenassCardid) {
        this.agenassCardid = agenassCardid;
    }

    public String getAgenassAddr() {
        return agenassAddr;
    }

    public void setAgenassAddr(String agenassAddr) {
        this.agenassAddr = agenassAddr;
    }

    public String getAgenassMoo() {
        return agenassMoo;
    }

    public void setAgenassMoo(String agenassMoo) {
        this.agenassMoo = agenassMoo;
    }

    public String getAgenassSoi() {
        return agenassSoi;
    }

    public void setAgenassSoi(String agenassSoi) {
        this.agenassSoi = agenassSoi;
    }

    public String getAgenassRoad() {
        return agenassRoad;
    }

    public void setAgenassRoad(String agenassRoad) {
        this.agenassRoad = agenassRoad;
    }

    public String getAgenassPostcode() {
        return agenassPostcode;
    }

    public void setAgenassPostcode(String agenassPostcode) {
        this.agenassPostcode = agenassPostcode;
    }

    public String getAgenassPhone() {
        return agenassPhone;
    }

    public void setAgenassPhone(String agenassPhone) {
        this.agenassPhone = agenassPhone;
    }

    public String getAgenassFax() {
        return agenassFax;
    }

    public void setAgenassFax(String agenassFax) {
        this.agenassFax = agenassFax;
    }

    public String getAgenassEmail() {
        return agenassEmail;
    }

    public void setAgenassEmail(String agenassEmail) {
        this.agenassEmail = agenassEmail;
    }

    public String getUseStatus() {
        return useStatus;
    }

    public void setUseStatus(String useStatus) {
        this.useStatus = useStatus;
    }

    public String getAndOrType() {
        return andOrType;
    }

    public void setAndOrType(String andOrType) {
        this.andOrType = andOrType;
    }

    public String getAgenKind() {
        return agenKind;
    }

    public void setAgenKind(String agenKind) {
        this.agenKind = agenKind;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TrwtNo04Agenass that = (TrwtNo04Agenass) o;
        return Objects.equals(agenassId, that.agenassId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(agenassId);
    }
}
