package th.co.geniustree.trademark.ocr.domain;

// default package
// Generated Jul 2, 2014 2:25:54 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.io.Serializable;
import java.util.Objects;

/**
 * TrwtNo02Rowner generated by hbm2java
 */

@Entity
@Table(name = "TRWT_NO02_ROWNER")
public class TrwtNo02Rowner extends BaseEntity implements Serializable {

    private static final long serialVersionUID = 7873276179542810724L;
    @Id
    @SequenceGenerator(name = "TRWT_NO02_ROWNER_SEQ", sequenceName = "TRWT_NO02_ROWNER_SEQ", initialValue = 1, allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "TRWT_NO02_ROWNER_SEQ")
    @Column(name = "ROWNER_ID", unique = true, nullable = false, precision = 15, scale = 0)
    private Long rownerId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TITLE_ID")
    private CtltTitle ctltTitle;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "LOC_ID")
    private CtltLocation ctltLocation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "OCCU_ID")
    private CtltOccupation ctltOccupation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TRW_NO02_ID")
    private TrwtNo02 trwtNo02;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "NAT_ID")
    private CtltNation ctltNation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "COUNTRY_ID")
    private CtltCountry ctltCountry;

    @Column(name = "ROWNER_TYPE", length = 1)
    private String rownerType;

    @Column(name = "ROWNER_NAME", length = 150)
    private String rownerName;

    @Column(name = "ROWNER_SURNAME", length = 150)
    private String rownerSurname;

    @Column(name = "ROWNER_CARDID", length = 50)
    private String rownerCardid;

    @Column(name = "ROWNER_ADDR", length = 150)
    private String rownerAddr;

    @Column(name = "ROWNER_SOI", length = 150)
    private String rownerSoi;

    @Column(name = "ROWNER_ROAD", length = 150)
    private String rownerRoad;

    @Column(name = "ROWNER_POSTCODE", length = 10)
    private String rownerPostcode;

    @Column(name = "ROWNER_PHONE", length = 50)
    private String rownerPhone;

    @Column(name = "ROWNER_FAX", length = 50)
    private String rownerFax;

    @Column(name = "ROWNER_EMAIL", length = 150)
    private String rownerEmail;

    @Column(name = "USE_STATUS", length = 1)
    private String useStatus;

    @Column(name = "ROWNER_MOO", length = 150)
    private String rownerMoo;

    public TrwtNo02Rowner() {
    }

    public TrwtNo02Rowner(Long rownerId) {
        this.rownerId = rownerId;
    }


    @Transient
    public Long getPk() {
        return rownerId;
    }

    public Long getRownerId() {
        return this.rownerId;
    }

    public void setRownerId(Long rownerId) {
        this.rownerId = rownerId;
    }

    public CtltTitle getCtltTitle() {
        return this.ctltTitle;
    }

    public void setCtltTitle(CtltTitle ctltTitle) {
        this.ctltTitle = ctltTitle;
    }

    public CtltLocation getCtltLocation() {
        return this.ctltLocation;
    }

    public void setCtltLocation(CtltLocation ctltLocation) {
        this.ctltLocation = ctltLocation;
    }

    public CtltOccupation getCtltOccupation() {
        return this.ctltOccupation;
    }

    public void setCtltOccupation(CtltOccupation ctltOccupation) {
        this.ctltOccupation = ctltOccupation;
    }

    public TrwtNo02 getTrwtNo02() {
        return this.trwtNo02;
    }

    public void setTrwtNo02(TrwtNo02 trwtNo02) {
        this.trwtNo02 = trwtNo02;
    }

    public CtltNation getCtltNation() {
        return this.ctltNation;
    }

    public void setCtltNation(CtltNation ctltNation) {
        this.ctltNation = ctltNation;
    }


    public CtltCountry getCtltCountry() {
        return this.ctltCountry;
    }

    public void setCtltCountry(CtltCountry ctltCountry) {
        this.ctltCountry = ctltCountry;
    }

    public String getRownerType() {
        return this.rownerType;
    }

    public void setRownerType(String rownerType) {
        this.rownerType = rownerType;
    }

    public String getRownerName() {
        return this.rownerName;
    }

    public void setRownerName(String rownerName) {
        this.rownerName = rownerName;
    }

    public String getRownerSurname() {
        return this.rownerSurname;
    }

    public void setRownerSurname(String rownerSurname) {
        this.rownerSurname = rownerSurname;
    }

    public String getRownerCardid() {
        return this.rownerCardid;
    }

    public void setRownerCardid(String rownerCardid) {
        this.rownerCardid = rownerCardid;
    }

    public String getRownerAddr() {
        return this.rownerAddr;
    }

    public void setRownerAddr(String rownerAddr) {
        this.rownerAddr = rownerAddr;
    }

    public String getRownerSoi() {
        return this.rownerSoi;
    }

    public void setRownerSoi(String rownerSoi) {
        this.rownerSoi = rownerSoi;
    }

    public String getRownerRoad() {
        return this.rownerRoad;
    }

    public void setRownerRoad(String rownerRoad) {
        this.rownerRoad = rownerRoad;
    }

    public String getRownerPostcode() {
        return this.rownerPostcode;
    }

    public void setRownerPostcode(String rownerPostcode) {
        this.rownerPostcode = rownerPostcode;
    }

    public String getRownerPhone() {
        return this.rownerPhone;
    }

    public void setRownerPhone(String rownerPhone) {
        this.rownerPhone = rownerPhone;
    }

    public String getRownerFax() {
        return this.rownerFax;
    }

    public void setRownerFax(String rownerFax) {
        this.rownerFax = rownerFax;
    }

    public String getRownerEmail() {
        return this.rownerEmail;
    }

    public void setRownerEmail(String rownerEmail) {
        this.rownerEmail = rownerEmail;
    }

    public String getUseStatus() {
        return this.useStatus;
    }

    public void setUseStatus(String useStatus) {
        this.useStatus = useStatus;
    }

    public String getRownerMoo() {
        return this.rownerMoo;
    }

    public void setRownerMoo(String rownerMoo) {
        this.rownerMoo = rownerMoo;
    }


    public String getFullCountry(){
        return getCtltCountry().getCountryName();
    }
    public String getFullOwnerAddress(){
        return getCtltLocation().getLocRepName();
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 89 * hash + Objects.hashCode(this.rownerId);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final TrwtNo02Rowner other = (TrwtNo02Rowner) obj;
        if (!Objects.equals(this.rownerId, other.rownerId)) {
            return false;
        }
        return true;
    }

}
