package th.co.geniustree.trademark.ocr.domain;

// default package
// Generated Jul 2, 2014 2:25:54 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.*;
import java.io.Serializable;
import java.util.Objects;

/**
 * TrwtNo02Ragency generated by hbm2java
 */

@Entity
@Table(name = "TRWT_NO02_RAGENCY")
public class TrwtNo02Ragency extends BaseEntity implements Serializable {

    private static final long serialVersionUID = 7513511799645825820L;
    @Id
    @SequenceGenerator(name = "TRWT_NO02_RAGENCY_SEQ", sequenceName = "TRWT_NO02_RAGENCY_SEQ", initialValue = 1, allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "TRWT_NO02_RAGENCY_SEQ")
    @Column(name = "RAGENCY_ID", unique = true, nullable = false, precision = 15, scale = 0)
    private Long ragencyId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TITLE_ID")
    private CtltTitle ctltTitle;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "LOC_ID")
    private CtltLocation ctltLocation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "OCCU_ID")
    private CtltOccupation ctltOccupation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TRW_NO02_ID")
    private TrwtNo02 trwtNo02;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "NAT_ID")
    private CtltNation ctltNation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "COUNTRY_ID")
    private CtltCountry ctltCountry;

    @Column(name = "RAGENCY_TYPE", length = 1)
    private String ragencyType;

    @Column(name = "RAGENCY_NAME", length = 150)
    private String ragencyName;

    @Column(name = "RAGENCY_SURNAME", length = 150)
    private String ragencySurname;

    @Column(name = "RAGENCY_CARDID", length = 50)
    private String ragencyCardid;

    @Column(name = "RAGENCY_ADDR", length = 150)
    private String ragencyAddr;

    @Column(name = "RAGENCY_SOI", length = 150)
    private String ragencySoi;

    @Column(name = "RAGENCY_ROAD", length = 150)
    private String ragencyRoad;

    @Column(name = "RAGENCY_POSTCODE", length = 10)
    private String ragencyPostcode;

    @Column(name = "RAGENCY_PHONE", length = 50)
    private String ragencyPhone;

    @Column(name = "RAGENCY_FAX", length = 50)
    private String ragencyFax;

    @Column(name = "RAGENCY_EMAIL", length = 150)
    private String ragencyEmail;

    @Column(name = "USE_STATUS", length = 1)
    private String useStatus;

    @Column(name = "RAGENCY_MOO", length = 150)
    private String ragencyMoo;

    @Column(name = "AND_OR_TYPE", length = 1)
    private String andOrType;

    @Column(name = "AGEN_KIND", length = 1)
    private String agenKind;

    public TrwtNo02Ragency() {
    }

    public TrwtNo02Ragency(Long ragencyId) {
        this.ragencyId = ragencyId;
    }

    @Transient
    public Long getPk() {
        return ragencyId;
    }


    public Long getRagencyId() {
        return this.ragencyId;
    }

    public void setRagencyId(Long ragencyId) {
        this.ragencyId = ragencyId;
    }

    public CtltTitle getCtltTitle() {
        return this.ctltTitle;
    }

    public void setCtltTitle(CtltTitle ctltTitle) {
        this.ctltTitle = ctltTitle;
    }

    public CtltLocation getCtltLocation() {
        return this.ctltLocation;
    }

    public void setCtltLocation(CtltLocation ctltLocation) {
        this.ctltLocation = ctltLocation;
    }

    public CtltOccupation getCtltOccupation() {
        return this.ctltOccupation;
    }

    public void setCtltOccupation(CtltOccupation ctltOccupation) {
        this.ctltOccupation = ctltOccupation;
    }

    public TrwtNo02 getTrwtNo02() {
        return this.trwtNo02;
    }

    public void setTrwtNo02(TrwtNo02 trwtNo02) {
        this.trwtNo02 = trwtNo02;
    }

    public CtltNation getCtltNation() {
        return this.ctltNation;
    }

    public void setCtltNation(CtltNation ctltNation) {
        this.ctltNation = ctltNation;
    }

    public CtltCountry getCtltCountry() {
        return this.ctltCountry;
    }

    public void setCtltCountry(CtltCountry ctltCountry) {
        this.ctltCountry = ctltCountry;
    }

    public String getRagencyType() {
        return this.ragencyType;
    }

    public void setRagencyType(String ragencyType) {
        this.ragencyType = ragencyType;
    }

    public String getRagencyName() {
        return this.ragencyName;
    }

    public void setRagencyName(String ragencyName) {
        this.ragencyName = ragencyName;
    }

    public String getRagencySurname() {
        return this.ragencySurname;
    }

    public void setRagencySurname(String ragencySurname) {
        this.ragencySurname = ragencySurname;
    }

    public String getRagencyCardid() {
        return this.ragencyCardid;
    }

    public void setRagencyCardid(String ragencyCardid) {
        this.ragencyCardid = ragencyCardid;
    }

    public String getRagencyAddr() {
        return this.ragencyAddr;
    }

    public void setRagencyAddr(String ragencyAddr) {
        this.ragencyAddr = ragencyAddr;
    }

    public String getRagencySoi() {
        return this.ragencySoi;
    }

    public void setRagencySoi(String ragencySoi) {
        this.ragencySoi = ragencySoi;
    }

    public String getRagencyRoad() {
        return this.ragencyRoad;
    }

    public void setRagencyRoad(String ragencyRoad) {
        this.ragencyRoad = ragencyRoad;
    }

    public String getRagencyPostcode() {
        return this.ragencyPostcode;
    }

    public void setRagencyPostcode(String ragencyPostcode) {
        this.ragencyPostcode = ragencyPostcode;
    }

    public String getRagencyPhone() {
        return this.ragencyPhone;
    }

    public void setRagencyPhone(String ragencyPhone) {
        this.ragencyPhone = ragencyPhone;
    }

    public String getRagencyFax() {
        return this.ragencyFax;
    }

    public void setRagencyFax(String ragencyFax) {
        this.ragencyFax = ragencyFax;
    }

    public String getRagencyEmail() {
        return this.ragencyEmail;
    }

    public void setRagencyEmail(String ragencyEmail) {
        this.ragencyEmail = ragencyEmail;
    }

    public String getUseStatus() {
        return this.useStatus;
    }

    public void setUseStatus(String useStatus) {
        this.useStatus = useStatus;
    }

    public String getRagencyMoo() {
        return this.ragencyMoo;
    }

    public void setRagencyMoo(String ragencyMoo) {
        this.ragencyMoo = ragencyMoo;
    }

    public String getAndOrType() {
        return andOrType;
    }

    public void setAndOrType(String andOrType) {
        this.andOrType = andOrType;
    }

    public String getAgenKind() {
        return agenKind;
    }

    public void setAgenKind(String agenKind) {
        this.agenKind = agenKind;
    }

    public String getFullCountry(){
        return getCtltCountry().getCountryName();
    }
    public String getfullAgencyAddress(){
        return getCtltLocation().getLocRepName();
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 13 * hash + Objects.hashCode(this.ragencyId);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final TrwtNo02Ragency other = (TrwtNo02Ragency) obj;
        if (!Objects.equals(this.ragencyId, other.ragencyId)) {
            return false;
        }
        return true;
    }

}
