package th.co.geniustree.trademark.ocr.domain;

// Generated Mar 12, 2014 1:41:25 PM by Hibernate Tools 3.4.0.CR1

import org.hibernate.validator.constraints.NotBlank;
import org.hibernate.validator.constraints.NotEmpty;


import javax.persistence.*;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Collection;
import java.util.Date;
import java.util.Objects;


/**
 * TrwtNo04 generated by hbm2java
 */

@Entity
@Table(name = "TRWT_NO04")
public class TrwtNo04 extends BaseEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @SequenceGenerator(name = "TRWT_NO04_SEQ", sequenceName = "TRWT_NO04_SEQ", initialValue = 1, allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "TRWT_NO04_SEQ")
    @Column(name = "TRW_NO04_ID", unique = true, nullable = false, precision = 22, scale = 0)
    private Long trwNo04Id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CONT_REC_LOC_ID")
    private CtltLocation ctltLocationByContRecLocId;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "TR_ID")
    private RpstTrademark rpstTrademark;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CONT_ASS_LOC_ID")
    private CtltLocation ctltLocationByContAssLocId;

    @Column(name = "TRW_TYPE", length = 1)
    private String trwType;

    @Temporal(TemporalType.DATE)
    @Column(name = "TRW_DATE", length = 7)
    private Date trwDate;

    @NotNull(message = "คำขอเลขที่ต้องไม่เป็นค่าว่าง")
    @Column(name = "TRW_REQ_NO", precision = 13, scale = 0)
    private Long trwReqNo;

    @Column(name = "TRW_REGIS_NO", length = 50)
    private String trwRegisNo;

    @Column(name = "CONT_ASS_TYPE")
    private String contAssType;

    @Column(name = "TRW_OWNER_LOETC")
    private String trwOwnerLoetc;

    @Column(name = "CONT_REC_TYPE")
    private String contRecType;

    @Column(name = "TRW_AGEN_LOETC")
    private String trwAgenLoetc;

    @Column(name = "TRW_CLAIM", length = 1)
    private String trwClaim;

    @NotBlank(message = "กรุณาแนบไฟล์")
    @Column(name = "TRW_REG_DOC")
    private String trwRegDoc;

    @Column(name = "TRW_ASSIGN_PIC")
    private String trwAssignPic;

    @Column(name = "TRW_RECEIPT_PIC")
    private String trwReceiptPic;

    @Column(name = "TRW_NOTARY_DOC")
    private String trwNotaryDoc;

    @Column(name = "TRW_CORP_DOC")
    private String trwCorpDoc;

    @Column(name = "TRW_AGREE_DOC")
    private String trwAgreeDoc;

    @Column(name = "TRW_AUTH_DOC")
    private String trwAuthDoc;

    @Column(name = "TRW_DEATH_DOC")
    private String trwDeathDoc;

    @Column(name = "TRW_HEIR_DOC")
    private String trwHeirDoc;

    @Column(name = "TRW_DEATH2_DOC")
    private String trwDeath2Doc;

    @Column(name = "TRW_TESTA_DOC")
    private String trwTestaDoc;

    @Column(name = "TRW_ESTATE_DOC")
    private String trwEstateDoc;

    @Column(name = "TRW_ESTATEID_PIC")
    private String trwEstateidPic;

    @Column(name = "TRW_HEIR_PIC")
    private String trwHeirPic;

    @Column(name = "TRW_ENFORCE_DOC")
    private String trwEnforceDoc;

    @Column(name = "FEE_AMOUNT", precision = 10)
    private BigDecimal feeAmount;

    @Column(name = "PAY_FLAG", length = 1)
    private String payFlag;

    @Column(name = "TRW_REF_NO", precision = 15, scale = 0)
    private Long trwRefNo;

    @Column(name = "CONT_REC_NAME", length = 150)
    private String contRecName;

    @Column(name = "CONT_REC_SURNAME", length = 150)
    private String contRecSurname;

    @Column(name = "CONT_REC_ADDR", length = 150)
    private String contRecAddr;

    @Column(name = "CONT_REC_MOO", length = 150)
    private String contRecMoo;

    @Column(name = "CONT_REC_SOI", length = 150)
    private String contRecSoi;

    @Column(name = "CONT_REC_ROAD", length = 150)
    private String contRecRoad;

    @Column(name = "CONT_REC_POSTCODE", length = 10)
    private String contRecPostcode;

    @Column(name = "CONT_REC_PHONE", length = 150)
    private String contRecPhone;

    @Column(name = "CONT_REC_FAX", length = 150)
    private String contRecFax;

    @Column(name = "CONT_REC_EMAIL", length = 150)
    private String contRecEmail;

    @Column(name = "CONT_ASS_NAME", length = 150)
    private String contAssName;

    @Column(name = "CONT_ASS_SURNAME", length = 150)
    private String contAssSurname;

    @Column(name = "CONT_ASS_ADDR", length = 150)
    private String contAssAddr;

    @Column(name = "CONT_ASS_MOO", length = 150)
    private String contAssMoo;

    @Column(name = "CONT_ASS_SOI", length = 150)
    private String contAssSoi;

    @Column(name = "CONT_ASS_ROAD", length = 150)
    private String contAssRoad;

    @Column(name = "CONT_ASS_POSTCODE", length = 10)
    private String contAssPostcode;

    @Column(name = "CONT_ASS_PHONE", length = 150)
    private String contAssPhone;

    @Column(name = "CONT_ASS_FAX", length = 150)
    private String contAssFax;

    @Column(name = "CONT_ASS_EMAIL", length = 150)
    private String contAssEmail;

    @Column(name = "FEE_CODE", length = 5)
    private String feeCode;

    @Column(name = "TRW_PDF_DOC", length = 255)
    private String trwPdfDoc;

    @Column(name = "TRW_GUARANTEE_DOC")
    private String trwGuaranteeDoc;

    @Valid
    @OneToMany(mappedBy = "trwtNo04", cascade = CascadeType.ALL, orphanRemoval = true)
    private Collection<TrwtNo04Agenass> trwtNo04Agenasses;

    @Valid
    @OneToMany(mappedBy = "trwtNo04", cascade = CascadeType.ALL, orphanRemoval = true)
    private Collection<TrwtNo04Agenrec> trwtNo04Agenrecs;

    @Valid
    @NotEmpty(message = "กรุณาเพิ่มข้อมูลเจ้าของ(ผู้โอน)")
    @OneToMany(mappedBy = "trwtNo04", cascade = CascadeType.ALL, orphanRemoval = true)
    private Collection<TrwtNo04Assign> trwtNo04Assigns;

    @NotEmpty(message = "รายการสินค้าต้องไม่เป็นค่าว่าง")
    @OneToMany(mappedBy = "trwtNo04", cascade = CascadeType.ALL, orphanRemoval = true)
    private Collection<TrwtNo04Nice> trwtNo04Nices;

    @Valid
    @NotEmpty(message = "กรุณาเพิ่มข้อมูลผู้รับโอน/ผู้รับมรดกสิทธิ")
    @OneToMany(mappedBy = "trwtNo04", cascade = CascadeType.ALL, orphanRemoval = true)
    private Collection<TrwtNo04Receipt> trwtNo04Receipts;


    public Long getTrwNo04Id() {
        return trwNo04Id;
    }

    public void setTrwNo04Id(Long trwNo04Id) {
        this.trwNo04Id = trwNo04Id;
    }

    public CtltLocation getCtltLocationByContRecLocId() {
        return ctltLocationByContRecLocId;
    }

    public void setCtltLocationByContRecLocId(CtltLocation ctltLocationByContRecLocId) {
        this.ctltLocationByContRecLocId = ctltLocationByContRecLocId;
    }

    public RpstTrademark getRpstTrademark() {
        return rpstTrademark;
    }

    public void setRpstTrademark(RpstTrademark rpstTrademark) {
        this.rpstTrademark = rpstTrademark;
    }

    public CtltLocation getCtltLocationByContAssLocId() {
        return ctltLocationByContAssLocId;
    }

    public void setCtltLocationByContAssLocId(CtltLocation ctltLocationByContAssLocId) {
        this.ctltLocationByContAssLocId = ctltLocationByContAssLocId;
    }

    public String getTrwType() {
        return trwType;
    }

    public void setTrwType(String trwType) {
        this.trwType = trwType;
    }

    public Date getTrwDate() {
        return trwDate;
    }

    public void setTrwDate(Date trwDate) {
        this.trwDate = trwDate;
    }

    public Long getTrwReqNo() {
        return trwReqNo;
    }

    public void setTrwReqNo(Long trwReqNo) {
        this.trwReqNo = trwReqNo;
    }

    public String getTrwRegisNo() {
        return trwRegisNo;
    }

    public void setTrwRegisNo(String trwRegisNo) {
        this.trwRegisNo = trwRegisNo;
    }

    public String getContAssType() {
        return contAssType;
    }

    public void setContAssType(String contAssType) {
        this.contAssType = contAssType;
    }

    public String getTrwOwnerLoetc() {
        return trwOwnerLoetc;
    }

    public void setTrwOwnerLoetc(String trwOwnerLoetc) {
        this.trwOwnerLoetc = trwOwnerLoetc;
    }

    public String getContRecType() {
        return contRecType;
    }

    public void setContRecType(String contRecType) {
        this.contRecType = contRecType;
    }

    public String getTrwAgenLoetc() {
        return trwAgenLoetc;
    }

    public void setTrwAgenLoetc(String trwAgenLoetc) {
        this.trwAgenLoetc = trwAgenLoetc;
    }

    public String getTrwClaim() {
        return trwClaim;
    }

    public void setTrwClaim(String trwClaim) {
        this.trwClaim = trwClaim;
    }

    public String getTrwRegDoc() {
        return trwRegDoc;
    }

    public void setTrwRegDoc(String trwRegDoc) {
        this.trwRegDoc = trwRegDoc;
    }

    public String getTrwAssignPic() {
        return trwAssignPic;
    }

    public void setTrwAssignPic(String trwAssignPic) {
        this.trwAssignPic = trwAssignPic;
    }

    public String getTrwReceiptPic() {
        return trwReceiptPic;
    }

    public void setTrwReceiptPic(String trwReceiptPic) {
        this.trwReceiptPic = trwReceiptPic;
    }

    public String getTrwNotaryDoc() {
        return trwNotaryDoc;
    }

    public void setTrwNotaryDoc(String trwNotaryDoc) {
        this.trwNotaryDoc = trwNotaryDoc;
    }

    public String getTrwCorpDoc() {
        return trwCorpDoc;
    }

    public void setTrwCorpDoc(String trwCorpDoc) {
        this.trwCorpDoc = trwCorpDoc;
    }

    public String getTrwAgreeDoc() {
        return trwAgreeDoc;
    }

    public void setTrwAgreeDoc(String trwAgreeDoc) {
        this.trwAgreeDoc = trwAgreeDoc;
    }

    public String getTrwAuthDoc() {
        return trwAuthDoc;
    }

    public void setTrwAuthDoc(String trwAuthDoc) {
        this.trwAuthDoc = trwAuthDoc;
    }

    public String getTrwDeathDoc() {
        return trwDeathDoc;
    }

    public void setTrwDeathDoc(String trwDeathDoc) {
        this.trwDeathDoc = trwDeathDoc;
    }

    public String getTrwHeirDoc() {
        return trwHeirDoc;
    }

    public void setTrwHeirDoc(String trwHeirDoc) {
        this.trwHeirDoc = trwHeirDoc;
    }

    public String getTrwDeath2Doc() {
        return trwDeath2Doc;
    }

    public void setTrwDeath2Doc(String trwDeath2Doc) {
        this.trwDeath2Doc = trwDeath2Doc;
    }

    public String getTrwTestaDoc() {
        return trwTestaDoc;
    }

    public void setTrwTestaDoc(String trwTestaDoc) {
        this.trwTestaDoc = trwTestaDoc;
    }

    public String getTrwEstateDoc() {
        return trwEstateDoc;
    }

    public void setTrwEstateDoc(String trwEstateDoc) {
        this.trwEstateDoc = trwEstateDoc;
    }

    public String getTrwEstateidPic() {
        return trwEstateidPic;
    }

    public void setTrwEstateidPic(String trwEstateidPic) {
        this.trwEstateidPic = trwEstateidPic;
    }

    public String getTrwHeirPic() {
        return trwHeirPic;
    }

    public void setTrwHeirPic(String trwHeirPic) {
        this.trwHeirPic = trwHeirPic;
    }

    public String getTrwEnforceDoc() {
        return trwEnforceDoc;
    }

    public void setTrwEnforceDoc(String trwEnforceDoc) {
        this.trwEnforceDoc = trwEnforceDoc;
    }

    public BigDecimal getFeeAmount() {
        return feeAmount;
    }

    public void setFeeAmount(BigDecimal feeAmount) {
        this.feeAmount = feeAmount;
    }

    public String getPayFlag() {
        return payFlag;
    }

    public void setPayFlag(String payFlag) {
        this.payFlag = payFlag;
    }

    public Long getTrwRefNo() {
        return trwRefNo;
    }

    public void setTrwRefNo(Long trwRefNo) {
        this.trwRefNo = trwRefNo;
    }

    public String getContRecName() {
        return contRecName;
    }

    public void setContRecName(String contRecName) {
        this.contRecName = contRecName;
    }

    public String getContRecSurname() {
        return contRecSurname;
    }

    public void setContRecSurname(String contRecSurname) {
        this.contRecSurname = contRecSurname;
    }

    public String getContRecAddr() {
        return contRecAddr;
    }

    public void setContRecAddr(String contRecAddr) {
        this.contRecAddr = contRecAddr;
    }

    public String getContRecMoo() {
        return contRecMoo;
    }

    public void setContRecMoo(String contRecMoo) {
        this.contRecMoo = contRecMoo;
    }

    public String getContRecSoi() {
        return contRecSoi;
    }

    public void setContRecSoi(String contRecSoi) {
        this.contRecSoi = contRecSoi;
    }

    public String getContRecRoad() {
        return contRecRoad;
    }

    public void setContRecRoad(String contRecRoad) {
        this.contRecRoad = contRecRoad;
    }

    public String getContRecPostcode() {
        return contRecPostcode;
    }

    public void setContRecPostcode(String contRecPostcode) {
        this.contRecPostcode = contRecPostcode;
    }

    public String getContRecPhone() {
        return contRecPhone;
    }

    public void setContRecPhone(String contRecPhone) {
        this.contRecPhone = contRecPhone;
    }

    public String getContRecFax() {
        return contRecFax;
    }

    public void setContRecFax(String contRecFax) {
        this.contRecFax = contRecFax;
    }

    public String getContRecEmail() {
        return contRecEmail;
    }

    public void setContRecEmail(String contRecEmail) {
        this.contRecEmail = contRecEmail;
    }

    public String getContAssName() {
        return contAssName;
    }

    public void setContAssName(String contAssName) {
        this.contAssName = contAssName;
    }

    public String getContAssSurname() {
        return contAssSurname;
    }

    public void setContAssSurname(String contAssSurname) {
        this.contAssSurname = contAssSurname;
    }

    public String getContAssAddr() {
        return contAssAddr;
    }

    public void setContAssAddr(String contAssAddr) {
        this.contAssAddr = contAssAddr;
    }

    public String getContAssMoo() {
        return contAssMoo;
    }

    public void setContAssMoo(String contAssMoo) {
        this.contAssMoo = contAssMoo;
    }

    public String getContAssSoi() {
        return contAssSoi;
    }

    public void setContAssSoi(String contAssSoi) {
        this.contAssSoi = contAssSoi;
    }

    public String getContAssRoad() {
        return contAssRoad;
    }

    public void setContAssRoad(String contAssRoad) {
        this.contAssRoad = contAssRoad;
    }

    public String getContAssPostcode() {
        return contAssPostcode;
    }

    public void setContAssPostcode(String contAssPostcode) {
        this.contAssPostcode = contAssPostcode;
    }

    public String getContAssPhone() {
        return contAssPhone;
    }

    public void setContAssPhone(String contAssPhone) {
        this.contAssPhone = contAssPhone;
    }

    public String getContAssFax() {
        return contAssFax;
    }

    public void setContAssFax(String contAssFax) {
        this.contAssFax = contAssFax;
    }

    public String getContAssEmail() {
        return contAssEmail;
    }

    public void setContAssEmail(String contAssEmail) {
        this.contAssEmail = contAssEmail;
    }

    public String getFeeCode() {
        return feeCode;
    }

    public void setFeeCode(String feeCode) {
        this.feeCode = feeCode;
    }

    public String getTrwPdfDoc() {
        return trwPdfDoc;
    }

    public void setTrwPdfDoc(String trwPdfDoc) {
        this.trwPdfDoc = trwPdfDoc;
    }

    public String getTrwGuaranteeDoc() {
        return trwGuaranteeDoc;
    }

    public void setTrwGuaranteeDoc(String trwGuaranteeDoc) {
        this.trwGuaranteeDoc = trwGuaranteeDoc;
    }

    public Collection<TrwtNo04Agenass> getTrwtNo04Agenasses() {
        return trwtNo04Agenasses;
    }

    public void setTrwtNo04Agenasses(Collection<TrwtNo04Agenass> trwtNo04Agenasses) {
        this.trwtNo04Agenasses = trwtNo04Agenasses;
    }

    public Collection<TrwtNo04Agenrec> getTrwtNo04Agenrecs() {
        return trwtNo04Agenrecs;
    }

    public void setTrwtNo04Agenrecs(Collection<TrwtNo04Agenrec> trwtNo04Agenrecs) {
        this.trwtNo04Agenrecs = trwtNo04Agenrecs;
    }

    public Collection<TrwtNo04Assign> getTrwtNo04Assigns() {
        return trwtNo04Assigns;
    }

    public void setTrwtNo04Assigns(Collection<TrwtNo04Assign> trwtNo04Assigns) {
        this.trwtNo04Assigns = trwtNo04Assigns;
    }

    public Collection<TrwtNo04Nice> getTrwtNo04Nices() {
        return trwtNo04Nices;
    }

    public void setTrwtNo04Nices(Collection<TrwtNo04Nice> trwtNo04Nices) {
        this.trwtNo04Nices = trwtNo04Nices;
    }

    public Collection<TrwtNo04Receipt> getTrwtNo04Receipts() {
        return trwtNo04Receipts;
    }

    public void setTrwtNo04Receipts(Collection<TrwtNo04Receipt> trwtNo04Receipts) {
        this.trwtNo04Receipts = trwtNo04Receipts;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TrwtNo04 trwtNo04 = (TrwtNo04) o;
        return Objects.equals(trwNo04Id, trwtNo04.trwNo04Id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(trwNo04Id);
    }
}
