package th.co.geniustree.trademark.ocr.domain;

// Generated Jan 2, 2014 10:59:53 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.io.Serializable;
import java.util.Objects;

/**
 * TrwtNo04Receipt generated by hbm2java
 */
@Entity
@Table(name = "TRWT_NO04_RECEIPT")
public class TrwtNo04Receipt extends BaseEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @SequenceGenerator(name = "TRWT_NO04_RECEIPT_SEQ", sequenceName = "TRWT_NO04_RECEIPT_SEQ", initialValue = 1, allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "TRWT_NO04_RECEIPT_SEQ")
    @Column(name = "RECEIPT_ID", unique = true, nullable = false, precision = 15, scale = 0)
    private Long receiptId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TITLE_ID")
    private CtltTitle ctltTitle;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "LOC_ID")
    private CtltLocation ctltLocation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "OCCU_ID")
    private CtltOccupation ctltOccupation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TRW_NO04_ID")
    private TrwtNo04 trwtNo04;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "NAT_ID")
    private CtltNation ctltNation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "COUNTRY_ID")
    private CtltCountry ctltCountry;

    @Column(name = "RECEIPT_TYPE", length = 1)
    private String receiptType;

    @Column(name = "RECEIPT_NAME", length = 150)
    private String receiptName;

    @Column(name = "RECEIPT_SURNAME", length = 150)
    private String receiptSurname;

    @Column(name = "RECEIPT_CARDID", length = 50)
    private String receiptCardid;

    @Column(name = "RECEIPT_ADDR", length = 150)
    private String receiptAddr;

    @Column(name = "RECEIPT_MOO", length = 150)
    private String receiptMoo;

    @Column(name = "RECEIPT_SOI", length = 150)
    private String receiptSoi;

    @Column(name = "RECEIPT_ROAD", length = 150)
    private String receiptRoad;

    @Column(name = "RECEIPT_POSTCODE", length = 10)
    private String receiptPostcode;

    @Column(name = "RECEIPT_PHONE", length = 50)
    private String receiptPhone;

    @Column(name = "RECEIPT_FAX", length = 50)
    private String receiptFax;

    @Column(name = "RECEIPT_EMAIL", length = 150)
    private String receiptEmail;

    @Column(name = "USE_STATUS", length = 1)
    private String useStatus;

    public Long getReceiptId() {
        return receiptId;
    }

    public void setReceiptId(Long receiptId) {
        this.receiptId = receiptId;
    }

    public CtltTitle getCtltTitle() {
        return ctltTitle;
    }

    public void setCtltTitle(CtltTitle ctltTitle) {
        this.ctltTitle = ctltTitle;
    }

    public CtltLocation getCtltLocation() {
        return ctltLocation;
    }

    public void setCtltLocation(CtltLocation ctltLocation) {
        this.ctltLocation = ctltLocation;
    }

    public CtltOccupation getCtltOccupation() {
        return ctltOccupation;
    }

    public void setCtltOccupation(CtltOccupation ctltOccupation) {
        this.ctltOccupation = ctltOccupation;
    }

    public TrwtNo04 getTrwtNo04() {
        return trwtNo04;
    }

    public void setTrwtNo04(TrwtNo04 trwtNo04) {
        this.trwtNo04 = trwtNo04;
    }

    public CtltNation getCtltNation() {
        return ctltNation;
    }

    public void setCtltNation(CtltNation ctltNation) {
        this.ctltNation = ctltNation;
    }

    public CtltCountry getCtltCountry() {
        return ctltCountry;
    }

    public void setCtltCountry(CtltCountry ctltCountry) {
        this.ctltCountry = ctltCountry;
    }

    public String getReceiptType() {
        return receiptType;
    }

    public void setReceiptType(String receiptType) {
        this.receiptType = receiptType;
    }

    public String getReceiptName() {
        return receiptName;
    }

    public void setReceiptName(String receiptName) {
        this.receiptName = receiptName;
    }

    public String getReceiptSurname() {
        return receiptSurname;
    }

    public void setReceiptSurname(String receiptSurname) {
        this.receiptSurname = receiptSurname;
    }

    public String getReceiptCardid() {
        return receiptCardid;
    }

    public void setReceiptCardid(String receiptCardid) {
        this.receiptCardid = receiptCardid;
    }

    public String getReceiptAddr() {
        return receiptAddr;
    }

    public void setReceiptAddr(String receiptAddr) {
        this.receiptAddr = receiptAddr;
    }

    public String getReceiptMoo() {
        return receiptMoo;
    }

    public void setReceiptMoo(String receiptMoo) {
        this.receiptMoo = receiptMoo;
    }

    public String getReceiptSoi() {
        return receiptSoi;
    }

    public void setReceiptSoi(String receiptSoi) {
        this.receiptSoi = receiptSoi;
    }

    public String getReceiptRoad() {
        return receiptRoad;
    }

    public void setReceiptRoad(String receiptRoad) {
        this.receiptRoad = receiptRoad;
    }

    public String getReceiptPostcode() {
        return receiptPostcode;
    }

    public void setReceiptPostcode(String receiptPostcode) {
        this.receiptPostcode = receiptPostcode;
    }

    public String getReceiptPhone() {
        return receiptPhone;
    }

    public void setReceiptPhone(String receiptPhone) {
        this.receiptPhone = receiptPhone;
    }

    public String getReceiptFax() {
        return receiptFax;
    }

    public void setReceiptFax(String receiptFax) {
        this.receiptFax = receiptFax;
    }

    public String getReceiptEmail() {
        return receiptEmail;
    }

    public void setReceiptEmail(String receiptEmail) {
        this.receiptEmail = receiptEmail;
    }

    public String getUseStatus() {
        return useStatus;
    }

    public void setUseStatus(String useStatus) {
        this.useStatus = useStatus;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TrwtNo04Receipt that = (TrwtNo04Receipt) o;
        return Objects.equals(receiptId, that.receiptId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(receiptId);
    }
}
