package th.co.geniustree.trademark.ocr.domain;

// Generated Jan 2, 2014 10:59:53 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.io.Serializable;
import java.util.Objects;

/**
 * TrwtNo04Nice generated by hbm2java
 */
@Entity
@Table(name = "TRWT_NO04_NICE")
public class TrwtNo04Nice extends BaseEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @SequenceGenerator(name = "TRWT_NO04_NICE_CLASS_SEQ", sequenceName = "TRWT_NO04_NICE_CLASS_SEQ", initialValue = 1, allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "TRWT_NO04_NICE_CLASS_SEQ")
    @Column(name = "TRW_NICE_CLASS_ID", unique = true, nullable = false, precision = 22, scale = 0)
    private Long trwNiceClassId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TRW_NO04_ID", nullable = false)
    private TrwtNo04 trwtNo04;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "NICE_CLASS_ID", nullable = false)
    private CtltNiceClass ctltNiceClass;

    @Column(name = "TRW_NO04_TYPE")
    private String trwNo04Type;

    @Column(name = "USE_STATUS", length = 1)
    private String useStatus;

    @ManyToOne
    @JoinColumn(name = "RPST_TR_GOODS_ID")
    private RpstTrGoods rpstTrGoods;

    public String getRpstTrGoodsJoining(){
        return getRpstTrGoods().getGoodsServices();
    }
    public String getClassCodeJoining(){
        return getRpstTrGoods().getClassCode();
    }

    public Long getTrwNiceClassId() {
        return trwNiceClassId;
    }

    public void setTrwNiceClassId(Long trwNiceClassId) {
        this.trwNiceClassId = trwNiceClassId;
    }

    public TrwtNo04 getTrwtNo04() {
        return trwtNo04;
    }

    public void setTrwtNo04(TrwtNo04 trwtNo04) {
        this.trwtNo04 = trwtNo04;
    }

    public CtltNiceClass getCtltNiceClass() {
        return ctltNiceClass;
    }

    public void setCtltNiceClass(CtltNiceClass ctltNiceClass) {
        this.ctltNiceClass = ctltNiceClass;
    }

    public String getTrwNo04Type() {
        return trwNo04Type;
    }

    public void setTrwNo04Type(String trwNo04Type) {
        this.trwNo04Type = trwNo04Type;
    }

    public String getUseStatus() {
        return useStatus;
    }

    public void setUseStatus(String useStatus) {
        this.useStatus = useStatus;
    }

    public RpstTrGoods getRpstTrGoods() {
        return rpstTrGoods;
    }

    public void setRpstTrGoods(RpstTrGoods rpstTrGoods) {
        this.rpstTrGoods = rpstTrGoods;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TrwtNo04Nice that = (TrwtNo04Nice) o;
        return Objects.equals(trwNiceClassId, that.trwNiceClassId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(trwNiceClassId);
    }
}
