package th.co.geniustree.trademark.ocr.domain;

// Generated Jan 2, 2014 10:59:53 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.io.Serializable;
import java.util.Objects;

/**
 * TrwtNo04Agenrec generated by hbm2java
 */
@Entity
@Table(name = "TRWT_NO04_AGENREC")
public class TrwtNo04Agenrec extends BaseEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @SequenceGenerator(name = "TRWT_NO04_AGENREC_SEQ", sequenceName = "TRWT_NO04_AGENREC_SEQ", initialValue = 1, allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "TRWT_NO04_AGENREC_SEQ")
    @Column(name = "AGENREC_ID", unique = true, nullable = false, precision = 15, scale = 0)
    private Long agenrecId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TITLE_ID")
    private CtltTitle ctltTitle;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "LOC_ID")
    private CtltLocation ctltLocation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "OCCU_ID")
    private CtltOccupation ctltOccupation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TRW_NO04_ID")
    private TrwtNo04 trwtNo04;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "NAT_ID")
    private CtltNation ctltNation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "COUNTRY_ID")
    private CtltCountry ctltCountry;

    @Column(name = "AGENREC_TYPE", length = 1)
    private String agenrecType;

    @Column(name = "AGENREC_NAME", length = 150)
    private String agenrecName;

    @Column(name = "AGENREC_SURNAME", length = 150)
    private String agenrecSurname;

    @Column(name = "AGENREC_CARDID", length = 50)
    private String agenrecCardid;

    @Column(name = "AGENREC_ADDR", length = 150)
    private String agenrecAddr;

    @Column(name = "AGENREC_MOO", length = 150)
    private String agenrecMoo;

    @Column(name = "AGENREC_SOI", length = 150)
    private String agenrecSoi;

    @Column(name = "AGENREC_ROAD", length = 150)
    private String agenrecRoad;

    @Column(name = "AGENREC_POSTCODE", length = 10)
    private String agenrecPostcode;

    @Column(name = "AGENREC_PHONE", length = 50)
    private String agenrecPhone;

    @Column(name = "AGENREC_FAX", length = 50)
    private String agenrecFax;

    @Column(name = "AGENREC_EMAIL", length = 150)
    private String agenrecEmail;

    @Column(name = "USE_STATUS", length = 1)
    private String useStatus;

    @Column(name = "AND_OR_TYPE", length = 1)
    private String andOrType;

    @Column(name = "AGEN_KIND", length = 1)
    private String agenKind;

    public Long getAgenrecId() {
        return agenrecId;
    }

    public void setAgenrecId(Long agenrecId) {
        this.agenrecId = agenrecId;
    }

    public CtltTitle getCtltTitle() {
        return ctltTitle;
    }

    public void setCtltTitle(CtltTitle ctltTitle) {
        this.ctltTitle = ctltTitle;
    }

    public CtltLocation getCtltLocation() {
        return ctltLocation;
    }

    public void setCtltLocation(CtltLocation ctltLocation) {
        this.ctltLocation = ctltLocation;
    }

    public CtltOccupation getCtltOccupation() {
        return ctltOccupation;
    }

    public void setCtltOccupation(CtltOccupation ctltOccupation) {
        this.ctltOccupation = ctltOccupation;
    }

    public TrwtNo04 getTrwtNo04() {
        return trwtNo04;
    }

    public void setTrwtNo04(TrwtNo04 trwtNo04) {
        this.trwtNo04 = trwtNo04;
    }

    public CtltNation getCtltNation() {
        return ctltNation;
    }

    public void setCtltNation(CtltNation ctltNation) {
        this.ctltNation = ctltNation;
    }

    public CtltCountry getCtltCountry() {
        return ctltCountry;
    }

    public void setCtltCountry(CtltCountry ctltCountry) {
        this.ctltCountry = ctltCountry;
    }

    public String getAgenrecType() {
        return agenrecType;
    }

    public void setAgenrecType(String agenrecType) {
        this.agenrecType = agenrecType;
    }

    public String getAgenrecName() {
        return agenrecName;
    }

    public void setAgenrecName(String agenrecName) {
        this.agenrecName = agenrecName;
    }

    public String getAgenrecSurname() {
        return agenrecSurname;
    }

    public void setAgenrecSurname(String agenrecSurname) {
        this.agenrecSurname = agenrecSurname;
    }

    public String getAgenrecCardid() {
        return agenrecCardid;
    }

    public void setAgenrecCardid(String agenrecCardid) {
        this.agenrecCardid = agenrecCardid;
    }

    public String getAgenrecAddr() {
        return agenrecAddr;
    }

    public void setAgenrecAddr(String agenrecAddr) {
        this.agenrecAddr = agenrecAddr;
    }

    public String getAgenrecMoo() {
        return agenrecMoo;
    }

    public void setAgenrecMoo(String agenrecMoo) {
        this.agenrecMoo = agenrecMoo;
    }

    public String getAgenrecSoi() {
        return agenrecSoi;
    }

    public void setAgenrecSoi(String agenrecSoi) {
        this.agenrecSoi = agenrecSoi;
    }

    public String getAgenrecRoad() {
        return agenrecRoad;
    }

    public void setAgenrecRoad(String agenrecRoad) {
        this.agenrecRoad = agenrecRoad;
    }

    public String getAgenrecPostcode() {
        return agenrecPostcode;
    }

    public void setAgenrecPostcode(String agenrecPostcode) {
        this.agenrecPostcode = agenrecPostcode;
    }

    public String getAgenrecPhone() {
        return agenrecPhone;
    }

    public void setAgenrecPhone(String agenrecPhone) {
        this.agenrecPhone = agenrecPhone;
    }

    public String getAgenrecFax() {
        return agenrecFax;
    }

    public void setAgenrecFax(String agenrecFax) {
        this.agenrecFax = agenrecFax;
    }

    public String getAgenrecEmail() {
        return agenrecEmail;
    }

    public void setAgenrecEmail(String agenrecEmail) {
        this.agenrecEmail = agenrecEmail;
    }

    public String getUseStatus() {
        return useStatus;
    }

    public void setUseStatus(String useStatus) {
        this.useStatus = useStatus;
    }

    public String getAndOrType() {
        return andOrType;
    }

    public void setAndOrType(String andOrType) {
        this.andOrType = andOrType;
    }

    public String getAgenKind() {
        return agenKind;
    }

    public void setAgenKind(String agenKind) {
        this.agenKind = agenKind;
    }

    public String getFullAgenrecAddress(){
        return getCtltLocation().getLocRepName();
    }
    public String getFullCountry(){
        return getCtltCountry().getCountryName();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TrwtNo04Agenrec that = (TrwtNo04Agenrec) o;
        return Objects.equals(agenrecId, that.agenrecId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(agenrecId);
    }
}
