package th.co.geniustree.trademark.ocr.domain;

// Generated Mar 12, 2014 1:41:25 PM by Hibernate Tools 3.4.0.CR1


import org.hibernate.validator.constraints.NotBlank;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.*;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import java.util.Objects;

/**
 * TrwtNo05 generated by hbm2java
 */


@Entity
@Table(name = "TRWT_NO05")
public class TrwtNo05 extends BaseEntity implements java.io.Serializable {

    private static final long serialVersionUID = -7542648092269450384L;
    @Id
    @SequenceGenerator(name = "TRWT_NO05_SEQ", sequenceName = "TRWT_NO05_SEQ", initialValue = 1, allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "TRWT_NO05_SEQ")
    @Column(name = "TRW_NO05_ID", unique = true, nullable = false, precision = 22, scale = 0)
    private Long trwNo05Id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TR_ID")
    private RpstTrademark rpstTrademark;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CONT_LOC_ID")
    private CtltLocation ctltLocation;

    @Column(name = "TRW_OPTION", length = 1)
    private String trwOption;

    @Column(name = "TRW_TYPE", length = 1)
    private String trwType;

    @Column(name = "TRW_DATE", length = 7)
    private LocalDate trwDate;

    @NotNull(message = "คำขอเลขที่ต้องไม่เป็นค่าว่าง")
    @Column(name = "TRW_REQ_NO", precision = 13, scale = 0)
    private Long trwReqNo;

    @Column(name = "TRW_REGIS_NO", length = 50)
    private String trwRegisNo;

    @Column(name = "TRW_LOCATION", length = 1)
    private String trwLocation;

    @Column(name = "TRW_LOCATION_DETAIL")
    private String trwLocationDetail;

    @Column(name = "TRW_LICENSE_DATE", length = 7)
    private LocalDate trwLicenseDate;

    @Column(name = "TRW_LICENSE_NO", length = 50)
    private String trwLicenseNo;

    @Column(name = "TRW_ONLYONE", length = 1)
    private String trwOnlyone;

    @Column(name = "TRW_RENEW", length = 1)
    private String trwRenew;

    @Column(name = "TRW_OTHER")
    private String trwOther;

   // @NotBlank(message="กรุณาแนบไฟล์")
    @Column(name = "TRW_REGIS_DOC")
    private String trwRegisDoc;

    @NotBlank(message="กรุณาแนบไฟล์")
    @Column(name = "TRW_LICENSE_DOC")
    private String trwLicenseDoc;

    @NotBlank(message="กรุณาแนบไฟล์")
    @Column(name = "TRW_CARDID_DOC")
    private String trwCardidDoc;

    @Column(name = "TRW_AUTH_DOC")
    private String trwAuthDoc;

    @Column(name = "TRW_NO20_DOC")
    private String trwNo20Doc;

    @Column(name = "FEE_AMOUNT", precision = 22, scale = 0)
    private BigDecimal feeAmount;

    @Column(name = "PAY_FLAG", length = 1)
    private String payFlag;

    @Column(name = "TRW_REF_NO", precision = 15, scale = 0)
    private Long trwRefNo;

    @Column(name = "CONT_NAME", length = 150)
    private String contName;

    @Column(name = "CONT_SURNAME", length = 150)
    private String contSurname;

    @Column(name = "CONT_ADDR", length = 150)
    private String contAddr;

    @Column(name = "CONT_MOO", length = 150)
    private String contMoo;

    @Column(name = "CONT_SOI", length = 150)
    private String contSoi;

    @Column(name = "CONT_ROAD", length = 150)
    private String contRoad;

    @Column(name = "CONT_POSTCODE", length = 10)
    private String contPostcode;

    @Column(name = "CONT_PHONE", length = 150)
    private String contPhone;

    @Column(name = "CONT_FAX", length = 150)
    private String contFax;

    @Column(name = "CONT_EMAIL", length = 150)
    private String contEmail;

    @Column(name = "FEE_CODE", length = 5)
    private String feeCode;

    @Column(name = "JOWNER_CONT_NAME", length = 150)
    private String jownerContName;

    @Column(name = "JOWNER_TRW_LOCATION", length = 1)
    private String jownerTrwLocation;

    @Column(name = "JOWNER_CONT_SURNAME", length = 150)
    private String jownerContSurname;

    @Column(name = "JOWNER_CONT_ADDR", length = 150)
    private String jownercontAddr;

    @Column(name = "JOWNER_CONT_MOO", length = 150)
    private String jownerContMoo;

    @Column(name = "JOWNER_CONT_SOI", length = 150)
    private String jownerContSoi;

    @Column(name = "JOWNER_CONT_ROAD", length = 150)
    private String jownerContRoad;

    @Column(name = "JOWNER_CONT_POSTCODE", length = 10)
    private String jownerContPostcode;

    @Column(name = "JOWNER_CONT_PHONE", length = 150)
    private String jownerContPhone;

    @Column(name = "JOWNER_CONT_FAX", length = 150)
    private String jownerContFax;

    @Column(name = "JOWNER_CONT_EMAIL", length = 150)
    private String jownerContEmail;

    @Column(name = "OWNER_USE_RIGHT",length = 1)
    private String ownerUseRight;

    @Column(name = "OWNER_RIGHT",length = 1)
    private String ownerRight;

    @Column(name = "TRANSER_USE_RIGHT",length = 1)
    private String transferUseRight;

    @Column(name = "TRANSFER_RIGHT",length = 1)
    private String transferRight;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "JOWNER_CONT_LOC_ID")
    private CtltLocation jownerCtltLocation;

    @Column(name = "TRW_PDF_DOC", length = 255)
    private String trwPdfDoc;

    @Column(name = "TRW_REQUEST_AMOUNT", precision = 22, scale = 0)
    private BigDecimal trwRequestAmount;

    @Column(name = "TRW_REQUEST_DETAILS")
    private String trwRequestDetails;

    @Valid
    @NotEmpty(message = "กรุณาเพิ่มข้อมูลเจ้าของ")
    @OneToMany(cascade = CascadeType.ALL,mappedBy = "trwtNo05",orphanRemoval = true)
    private List<TrwtNo05Owner> trwtNo05Owners;

    @Valid
    @OneToMany(cascade = CascadeType.ALL,mappedBy = "trwtNo05",orphanRemoval = true)
    private List<TrwtNo05Agency> trwtNo05Agencies;

    @Valid
    @NotEmpty(message = "กรุณาเพิ่มข้อมูลผู้ได้รับอนุญาต/ผู้ได้รับอนุญาตช่วง")
    @OneToMany(cascade = CascadeType.ALL,mappedBy = "trwtNo05",orphanRemoval = true)
    private List<TrwtNo05Jowner> trwtNo05Jowners;

    @Valid
    @OneToMany(cascade = CascadeType.ALL,mappedBy = "trwtNo05",orphanRemoval = true)
    private List<TrwtNo05Jagency> trwtNo05Jagencies;

    @OneToMany(cascade = CascadeType.ALL,mappedBy = "trwtNo05",orphanRemoval = true)
    private List<TrwtNo05Class> trwtNo05Classes;

    @OneToMany(cascade = CascadeType.ALL,mappedBy = "trwtNo05",orphanRemoval = true)
    private List<TrwtNo05Goods> trwtNo05GoodsList;

    public Long getTrwNo05Id() {
        return this.trwNo05Id;
    }

    public void setTrwNo05Id(Long trwNo05Id) {
        this.trwNo05Id = trwNo05Id;
    }

    public RpstTrademark getRpstTrademark() {
        return this.rpstTrademark;
    }

    public void setRpstTrademark(RpstTrademark rpstTrademark) {
        this.rpstTrademark = rpstTrademark;
    }


     public CtltLocation getCtltLocation() {
        return this.ctltLocation;
    }

    public void setCtltLocation(CtltLocation ctltLocation) {
        this.ctltLocation = ctltLocation;
    }

    public String getTrwOption() {
        return this.trwOption;
    }

    public void setTrwOption(String trwOption) {
        this.trwOption = trwOption;
    }

    public String getTrwType() {
        return this.trwType;
    }

    public void setTrwType(String trwType) {
        this.trwType = trwType;
    }

    public LocalDate getTrwDate() {
        return this.trwDate;
    }

    public void setTrwDate(LocalDate trwDate) {
        this.trwDate = trwDate;
    }

    public Long getTrwReqNo() {
        return this.trwReqNo;
    }

    public void setTrwReqNo(Long trwReqNo) {
        this.trwReqNo = trwReqNo;
    }

    public String getTrwRegisNo() {
        return this.trwRegisNo;
    }

    public void setTrwRegisNo(String trwRegisNo) {
        this.trwRegisNo = trwRegisNo;
    }

     public String getTrwLocation() {
        return this.trwLocation;
    }

    public void setTrwLocation(String trwLocation) {
        this.trwLocation = trwLocation;
    }

    public String getTrwLocationDetail() {
        return this.trwLocationDetail;
    }

    public void setTrwLocationDetail(String trwLocationDetail) {
        this.trwLocationDetail = trwLocationDetail;
    }

    public LocalDate getTrwLicenseDate() {
        return this.trwLicenseDate;
    }

    public void setTrwLicenseDate(LocalDate trwLicenseDate) {
        this.trwLicenseDate = trwLicenseDate;
    }

    public String getTrwLicenseNo() {
        return this.trwLicenseNo;
    }

    public void setTrwLicenseNo(String trwLicenseNo) {
        this.trwLicenseNo = trwLicenseNo;
    }

    public String getTrwOnlyone() {
        return this.trwOnlyone;
    }

    public void setTrwOnlyone(String trwOnlyone) {
        this.trwOnlyone = trwOnlyone;
    }

    public String getTrwRenew() {
        return this.trwRenew;
    }

    public void setTrwRenew(String trwRenew) {
        this.trwRenew = trwRenew;
    }

    public String getTrwOther() {
        return this.trwOther;
    }

    public void setTrwOther(String trwOther) {
        this.trwOther = trwOther;
    }

    public String getTrwRegisDoc() {
        return this.trwRegisDoc;
    }

    public void setTrwRegisDoc(String trwRegisDoc) {
        this.trwRegisDoc = trwRegisDoc;
    }

    public String getTrwLicenseDoc() {
        return this.trwLicenseDoc;
    }

    public void setTrwLicenseDoc(String trwLicenseDoc) {
        this.trwLicenseDoc = trwLicenseDoc;
    }

    public String getTrwCardidDoc() {
        return this.trwCardidDoc;
    }

    public void setTrwCardidDoc(String trwCardidDoc) {
        this.trwCardidDoc = trwCardidDoc;
    }

    public String getTrwAuthDoc() {
        return this.trwAuthDoc;
    }

    public void setTrwAuthDoc(String trwAuthDoc) {
        this.trwAuthDoc = trwAuthDoc;
    }

    public String getTrwNo20Doc() {
        return this.trwNo20Doc;
    }

    public void setTrwNo20Doc(String trwNo20Doc) {
        this.trwNo20Doc = trwNo20Doc;
    }

    public BigDecimal getFeeAmount() {
        return this.feeAmount;
    }

    public void setFeeAmount(BigDecimal feeAmount) {
        this.feeAmount = feeAmount;
    }

    public String getPayFlag() {
        return this.payFlag;
    }

    public void setPayFlag(String payFlag) {
        this.payFlag = payFlag;
    }

    public Long getTrwRefNo() {
        return this.trwRefNo;
    }

    public void setTrwRefNo(Long trwRefNo) {
        this.trwRefNo = trwRefNo;
    }


    public String getContName() {
        return this.contName;
    }

    public void setContName(String contName) {
        this.contName = contName;
    }

    public String getContSurname() {
        return this.contSurname;
    }

    public void setContSurname(String contSurname) {
        this.contSurname = contSurname;
    }

     public String getContAddr() {
        return this.contAddr;
    }

    public void setContAddr(String contAddr) {
        this.contAddr = contAddr;
    }

     public String getContMoo() {
        return this.contMoo;
    }

    public void setContMoo(String contMoo) {
        this.contMoo = contMoo;
    }

     public String getContSoi() {
        return this.contSoi;
    }

    public void setContSoi(String contSoi) {
        this.contSoi = contSoi;
    }

     public String getContRoad() {
        return this.contRoad;
    }

    public void setContRoad(String contRoad) {
        this.contRoad = contRoad;
    }

     public String getContPostcode() {
        return this.contPostcode;
    }

    public void setContPostcode(String contPostcode) {
        this.contPostcode = contPostcode;
    }

     public String getContPhone() {
        return this.contPhone;
    }

    public void setContPhone(String contPhone) {
        this.contPhone = contPhone;
    }

     public String getContFax() {
        return this.contFax;
    }

    public void setContFax(String contFax) {
        this.contFax = contFax;
    }

     public String getContEmail() {
        return this.contEmail;
    }

    public void setContEmail(String contEmail) {
        this.contEmail = contEmail;
    }

    public String getFeeCode() {
        return feeCode;
    }

    public void setFeeCode(String feeCode) {
        this.feeCode = feeCode;
    }

    public String getTrwPdfDoc() {
        return trwPdfDoc;
    }

    public void setTrwPdfDoc(String trwPdfDoc) {
        this.trwPdfDoc = trwPdfDoc;
    }

    public BigDecimal getTrwRequestAmount() {
        return trwRequestAmount;
    }

    public void setTrwRequestAmount(BigDecimal trwRequestAmount) {
        this.trwRequestAmount = trwRequestAmount;
    }

    public String getTrwRequestDetails() {
        return trwRequestDetails;
    }

    public void setTrwRequestDetails(String trwRequestDetails) {
        this.trwRequestDetails = trwRequestDetails;
    }

    public List<TrwtNo05Owner> getTrwtNo05Owners() {
        return trwtNo05Owners;
    }

    public void setTrwtNo05Owners(List<TrwtNo05Owner> trwtNo05Owners) {
        this.trwtNo05Owners = trwtNo05Owners;
    }

    public List<TrwtNo05Agency> getTrwtNo05Agencies() {
        return trwtNo05Agencies;
    }

    public void setTrwtNo05Agencies(List<TrwtNo05Agency> trwtNo05Agencies) {
        this.trwtNo05Agencies = trwtNo05Agencies;
    }

    public List<TrwtNo05Jowner> getTrwtNo05Jowners() {
        return trwtNo05Jowners;
    }

    public void setTrwtNo05Jowners(List<TrwtNo05Jowner> trwtNo05Jowners) {
        this.trwtNo05Jowners = trwtNo05Jowners;
    }

    public List<TrwtNo05Jagency> getTrwtNo05Jagencies() {
        return trwtNo05Jagencies;
    }

    public void setTrwtNo05Jagencies(List<TrwtNo05Jagency> trwtNo05Jagencies) {
        this.trwtNo05Jagencies = trwtNo05Jagencies;
    }

    public List<TrwtNo05Class> getTrwtNo05Classes() {
        return trwtNo05Classes;
    }

    public String getOwnerUseRight() {
        return ownerUseRight;
    }

    public void setOwnerUseRight(String ownerUseRight) {
        this.ownerUseRight = ownerUseRight;
    }

    public String getOwnerRight() {
        return ownerRight;
    }

    public void setOwnerRight(String ownerRight) {
        this.ownerRight = ownerRight;
    }

    public String getTransferUseRight() {
        return transferUseRight;
    }

    public void setTransferUseRight(String transferUseRight) {
        this.transferUseRight = transferUseRight;
    }

    public String getTransferRight() {
        return transferRight;
    }

    public void setTransferRight(String transferRight) {
        this.transferRight = transferRight;
    }

    public void setTrwtNo05Classes(List<TrwtNo05Class> trwtNo05Classes) {
        this.trwtNo05Classes = trwtNo05Classes;
    }

    public String getJownerTrwLocation() {
        return jownerTrwLocation;
    }

    public void setJownerTrwLocation(String jownerTrwLocation) {
        this.jownerTrwLocation = jownerTrwLocation;
    }

    public String getJownerContName() {
        return jownerContName;
    }

    public void setJownerContName(String jownerContName) {
        this.jownerContName = jownerContName;
    }

    public String getJownerContSurname() {
        return jownerContSurname;
    }

    public void setJownerContSurname(String jownerContSurname) {
        this.jownerContSurname = jownerContSurname;
    }

    public String getJownercontAddr() {
        return jownercontAddr;
    }

    public void setJownercontAddr(String jownercontAddr) {
        this.jownercontAddr = jownercontAddr;
    }

    public String getJownerContMoo() {
        return jownerContMoo;
    }

    public void setJownerContMoo(String jownerContMoo) {
        this.jownerContMoo = jownerContMoo;
    }

    public String getJownerContSoi() {
        return jownerContSoi;
    }

    public void setJownerContSoi(String jownerContSoi) {
        this.jownerContSoi = jownerContSoi;
    }

    public String getJownerContRoad() {
        return jownerContRoad;
    }

    public void setJownerContRoad(String jownerContRoad) {
        this.jownerContRoad = jownerContRoad;
    }

    public String getJownerContPostcode() {
        return jownerContPostcode;
    }

    public void setJownerContPostcode(String jownerContPostcode) {
        this.jownerContPostcode = jownerContPostcode;
    }

    public String getJownerContPhone() {
        return jownerContPhone;
    }

    public void setJownerContPhone(String jownerContPhone) {
        this.jownerContPhone = jownerContPhone;
    }

    public String getJownerContFax() {
        return jownerContFax;
    }

    public void setJownerContFax(String jownerContFax) {
        this.jownerContFax = jownerContFax;
    }

    public String getJownerContEmail() {
        return jownerContEmail;
    }

    public void setJownerContEmail(String jownerContEmail) {
        this.jownerContEmail = jownerContEmail;
    }

    public CtltLocation getJownerCtltLocation() {
        return jownerCtltLocation;
    }

    public void setJownerCtltLocation(CtltLocation jownerCtltLocation) {
        this.jownerCtltLocation = jownerCtltLocation;
    }

    public List<TrwtNo05Goods> getTrwtNo05GoodsList() {
        return trwtNo05GoodsList;
    }

    public void setTrwtNo05GoodsList(List<TrwtNo05Goods> trwtNo05GoodsList) {
        this.trwtNo05GoodsList = trwtNo05GoodsList;
    }


    @Override
    public int hashCode() {
        int hash = 5;
        hash = 89 * hash + Objects.hashCode(this.trwNo05Id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final TrwtNo05 other = (TrwtNo05) obj;
        if (!Objects.equals(this.trwNo05Id, other.trwNo05Id)) {
            return false;
        }
        return true;
    }

}
