package th.co.geniustree.trademark.ocr.domain;

// Generated Jan 2, 2014 10:59:53 AM by Hibernate Tools 3.4.0.CR1


import javax.persistence.*;
import java.io.Serializable;
import java.util.Objects;

/**
 * TrwtNo04Assign generated by hbm2java
 */

@Entity
@Table(name = "TRWT_NO04_ASSIGN")
public class TrwtNo04Assign extends BaseEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @SequenceGenerator(name = "TRWT_NO04_ASSIGN_SEQ", sequenceName = "TRWT_NO04_ASSIGN_SEQ", initialValue = 1, allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "TRWT_NO04_ASSIGN_SEQ")
    @Column(name = "ASSIGN_ID", unique = true, nullable = false, precision = 15, scale = 0)
    private Long assignId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TITLE_ID")
    private CtltTitle ctltTitle;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "LOC_ID")
    private CtltLocation ctltLocation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "OCCU_ID")
    private CtltOccupation ctltOccupation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TRW_NO04_ID")
    private TrwtNo04 trwtNo04;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "NAT_ID")
    private CtltNation ctltNation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "COUNTRY_ID")
    private CtltCountry ctltCountry;

    @Column(name = "ASSIGN_TYPE", length = 1)
    private String assignType;

    @Column(name = "ASSIGN_NAME", length = 150)
    private String assignName;

    @Column(name = "ASSIGN_SURNAME", length = 150)
    private String assignSurname;

    @Column(name = "ASSIGN_CARDID", length = 50)
    private String assignCardid;

    @Column(name = "ASSIGN_ADDR", length = 150)
    private String assignAddr;

    @Column(name = "ASSIGN_MOO", length = 150)
    private String assignMoo;

    @Column(name = "ASSIGN_SOI", length = 150)
    private String assignSoi;

    @Column(name = "ASSIGN_ROAD", length = 150)
    private String assignRoad;

    @Column(name = "ASSIGN_POSTCODE", length = 10)
    private String assignPostcode;

    @Column(name = "ASSIGN_PHONE", length = 50)
    private String assignPhone;

    @Column(name = "ASSIGN_FAX", length = 50)
    private String assignFax;

    @Column(name = "ASSIGN_EMAIL", length = 150)
    private String assignEmail;

    @Column(name = "USE_STATUS", length = 1)
    private String useStatus;

    public Long getAssignId() {
        return assignId;
    }

    public void setAssignId(Long assignId) {
        this.assignId = assignId;
    }

    public CtltTitle getCtltTitle() {
        return ctltTitle;
    }

    public void setCtltTitle(CtltTitle ctltTitle) {
        this.ctltTitle = ctltTitle;
    }

    public CtltLocation getCtltLocation() {
        return ctltLocation;
    }

    public void setCtltLocation(CtltLocation ctltLocation) {
        this.ctltLocation = ctltLocation;
    }

    public CtltOccupation getCtltOccupation() {
        return ctltOccupation;
    }

    public void setCtltOccupation(CtltOccupation ctltOccupation) {
        this.ctltOccupation = ctltOccupation;
    }

    public TrwtNo04 getTrwtNo04() {
        return trwtNo04;
    }

    public void setTrwtNo04(TrwtNo04 trwtNo04) {
        this.trwtNo04 = trwtNo04;
    }

    public CtltNation getCtltNation() {
        return ctltNation;
    }

    public void setCtltNation(CtltNation ctltNation) {
        this.ctltNation = ctltNation;
    }

    public CtltCountry getCtltCountry() {
        return ctltCountry;
    }

    public void setCtltCountry(CtltCountry ctltCountry) {
        this.ctltCountry = ctltCountry;
    }

    public String getAssignType() {
        return assignType;
    }

    public void setAssignType(String assignType) {
        this.assignType = assignType;
    }

    public String getAssignName() {
        return assignName;
    }

    public void setAssignName(String assignName) {
        this.assignName = assignName;
    }

    public String getAssignSurname() {
        return assignSurname;
    }

    public void setAssignSurname(String assignSurname) {
        this.assignSurname = assignSurname;
    }

    public String getAssignCardid() {
        return assignCardid;
    }

    public void setAssignCardid(String assignCardid) {
        this.assignCardid = assignCardid;
    }

    public String getAssignAddr() {
        return assignAddr;
    }

    public void setAssignAddr(String assignAddr) {
        this.assignAddr = assignAddr;
    }

    public String getAssignMoo() {
        return assignMoo;
    }

    public void setAssignMoo(String assignMoo) {
        this.assignMoo = assignMoo;
    }

    public String getAssignSoi() {
        return assignSoi;
    }

    public void setAssignSoi(String assignSoi) {
        this.assignSoi = assignSoi;
    }

    public String getAssignRoad() {
        return assignRoad;
    }

    public void setAssignRoad(String assignRoad) {
        this.assignRoad = assignRoad;
    }

    public String getAssignPostcode() {
        return assignPostcode;
    }

    public void setAssignPostcode(String assignPostcode) {
        this.assignPostcode = assignPostcode;
    }

    public String getAssignPhone() {
        return assignPhone;
    }

    public void setAssignPhone(String assignPhone) {
        this.assignPhone = assignPhone;
    }

    public String getAssignFax() {
        return assignFax;
    }

    public void setAssignFax(String assignFax) {
        this.assignFax = assignFax;
    }

    public String getAssignEmail() {
        return assignEmail;
    }

    public void setAssignEmail(String assignEmail) {
        this.assignEmail = assignEmail;
    }

    public String getUseStatus() {
        return useStatus;
    }

    public void setUseStatus(String useStatus) {
        this.useStatus = useStatus;
    }

    public String getFullAssignAddress(){
        return getCtltLocation().getLocRepName();
    }
    public String getFullCountry(){
        return getCtltCountry().getCountryName();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TrwtNo04Assign that = (TrwtNo04Assign) o;
        return Objects.equals(assignId, that.assignId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(assignId);
    }
}
