package th.co.geniustree.trademark.ocr.domain;

// Generated Nov 27, 2013 11:05:02 AM by Hibernate Tools 3.4.0.CR1


import javax.persistence.*;
import java.util.Objects;

/**
 * TrwtNo05Agency generated by hbm2java
 */
@Entity
@Table(name = "TRWT_NO05_AGENCY")
public class TrwtNo05Agency extends BaseEntity implements java.io.Serializable {

    private static final long serialVersionUID = -1540915245689685560L;
    @Id
    @SequenceGenerator(name = "TRWT_NO05_AGENCY_SEQ", sequenceName = "TRWT_NO05_AGENCY_SEQ", initialValue = 1, allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "TRWT_NO05_AGENCY_SEQ")
    @Column(name = "AGENCY_ID", unique = true, nullable = false, precision = 15, scale = 0)
    private Long agencyId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TITLE_ID")
    private CtltTitle ctltTitle;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "LOC_ID")
    private CtltLocation ctltLocation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "OCCU_ID")
    private CtltOccupation ctltOccupation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TRW_NO05_ID")
    private TrwtNo05 trwtNo05;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "NAT_ID")
    private CtltNation ctltNation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "COUNTRY_ID")
    private CtltCountry ctltCountry;

    @Column(name = "AGENCY_TYPE", length = 1)
    private String agencyType;

    @Column(name = "AGENCY_NAME", length = 150)
    private String agencyName;

    @Column(name = "AGENCY_SURNAME", length = 150)
    private String agencySurname;

    @Column(name = "AGENCY_CARDID", length = 50)
    private String agencyCardid;

    @Column(name = "AGENCY_ADDR", length = 150)
    private String agencyAddr;

    @Column(name = "AGENCY_MOO", length = 150)
    private String agencyMoo;

    @Column(name = "AGENCY_SOI", length = 150)
    private String agencySoi;

    @Column(name = "AGENCY_ROAD", length = 150)
    private String agencyRoad;

    @Column(name = "AGENCY_POSTCODE", length = 10)
    private String agencyPostcode;

    @Column(name = "AGENCY_PHONE", length = 50)
    private String agencyPhone;

    @Column(name = "AGENCY_FAX", length = 50)
    private String agencyFax;

    @Column(name = "AGENCY_EMAIL", length = 150)
    private String agencyEmail;

    @Column(name = "USE_STATUS", length = 1)
    private String useStatus;

    @Column(name = "AND_OR_TYPE", length = 1)
    private String andOrType;

    @Column(name = "AGEN_KIND", length = 1)
    private String agenKind;



     public Long getAgencyId() {
        return this.agencyId;
    }

    public void setAgencyId(Long agencyId) {
        this.agencyId = agencyId;
    }

     public CtltTitle getCtltTitle() {
        return this.ctltTitle;
    }

    public void setCtltTitle(CtltTitle ctltTitle) {
        this.ctltTitle = ctltTitle;
    }

     public CtltLocation getCtltLocation() {
        return this.ctltLocation;
    }

    public void setCtltLocation(CtltLocation ctltLocation) {
        this.ctltLocation = ctltLocation;
    }


     public CtltOccupation getCtltOccupation() {
        return this.ctltOccupation;
    }

    public void setCtltOccupation(CtltOccupation ctltOccupation) {
        this.ctltOccupation = ctltOccupation;
    }

    public TrwtNo05 getTrwtNo05() {
        return this.trwtNo05;
    }

    public void setTrwtNo05(TrwtNo05 trwtNo05) {
        this.trwtNo05 = trwtNo05;
    }

     public CtltNation getCtltNation() {
        return this.ctltNation;
    }

    public void setCtltNation(CtltNation ctltNation) {
        this.ctltNation = ctltNation;
    }

     public CtltCountry getCtltCountry() {
        return this.ctltCountry;
    }

    public void setCtltCountry(CtltCountry ctltCountry) {
        this.ctltCountry = ctltCountry;
    }

     public String getAgencyType() {
        return this.agencyType;
    }

    public void setAgencyType(String agencyType) {
        this.agencyType = agencyType;
    }

     public String getAgencyName() {
        return this.agencyName;
    }

    public void setAgencyName(String agencyName) {
        this.agencyName = agencyName;
    }

     public String getAgencySurname() {
        return this.agencySurname;
    }

    public void setAgencySurname(String agencySurname) {
        this.agencySurname = agencySurname;
    }

     public String getAgencyCardid() {
        return this.agencyCardid;
    }

    public void setAgencyCardid(String agencyCardid) {
        this.agencyCardid = agencyCardid;
    }

     public String getAgencyAddr() {
        return this.agencyAddr;
    }

    public void setAgencyAddr(String agencyAddr) {
        this.agencyAddr = agencyAddr;
    }

     public String getAgencySoi() {
        return this.agencySoi;
    }

    public void setAgencySoi(String agencySoi) {
        this.agencySoi = agencySoi;
    }

     public String getAgencyRoad() {
        return this.agencyRoad;
    }

    public void setAgencyRoad(String agencyRoad) {
        this.agencyRoad = agencyRoad;
    }

     public String getAgencyPostcode() {
        return this.agencyPostcode;
    }

    public void setAgencyPostcode(String agencyPostcode) {
        this.agencyPostcode = agencyPostcode;
    }

     public String getAgencyPhone() {
        return this.agencyPhone;
    }

    public void setAgencyPhone(String agencyPhone) {
        this.agencyPhone = agencyPhone;
    }

     public String getAgencyFax() {
        return this.agencyFax;
    }

    public void setAgencyFax(String agencyFax) {
        this.agencyFax = agencyFax;
    }

     public String getAgencyEmail() {
        return this.agencyEmail;
    }

    public void setAgencyEmail(String agencyEmail) {
        this.agencyEmail = agencyEmail;
    }

     public String getUseStatus() {
        return this.useStatus;
    }

    public void setUseStatus(String useStatus) {
        this.useStatus = useStatus;
    }

     public String getAgencyMoo() {
        return agencyMoo;
    }

    public void setAgencyMoo(String agencyMoo) {
        this.agencyMoo = agencyMoo;
    }

     public String getAndOrType() {
        return andOrType;
    }

    public void setAndOrType(String andOrType) {
        this.andOrType = andOrType;
    }

     public String getAgenKind() {
        return agenKind;
    }

    public void setAgenKind(String agenKind) {
        this.agenKind = agenKind;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 79 * hash + Objects.hashCode(this.agencyId);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final TrwtNo05Agency other = (TrwtNo05Agency) obj;
        if (!Objects.equals(this.agencyId, other.agencyId)) {
            return false;
        }
        return true;
    }

}
